export interface RedFlagSet {
  id: string;
  title: string;
  description: string;
  difficulty: number;
  statements: FlagStatement[];
}

export interface FlagStatement {
  id: string;
  text: string;
  speaker: string;
  context: string;
  isRedFlag: boolean;
  explanation: string;
  category: 'manipulation' | 'boundary_violation' | 'gaslighting' | 'love_bombing' | 'control' | 'healthy' | 'assertive' | 'empathetic';
}

export const RED_FLAG_SETS: RedFlagSet[] = [
  {
    id: 'dating_signals',
    title: 'Dating Red & Green Flags',
    description: 'Spot the warning signs and healthy behaviors in early dating',
    difficulty: 1,
    statements: [
      {
        id: 'ds_1',
        text: '"I\'ve never felt this way about anyone. You\'re my soulmate and we\'ve only been dating two weeks."',
        speaker: 'New partner',
        context: 'Second week of dating',
        isRedFlag: true,
        explanation: 'Love bombing — excessive intensity too early is a manipulation tactic, not genuine connection. Healthy relationships build gradually.',
        category: 'love_bombing',
      },
      {
        id: 'ds_2',
        text: '"I had a great time tonight. I\'d love to see you again this weekend if you\'re free."',
        speaker: 'Date',
        context: 'End of a third date',
        isRedFlag: false,
        explanation: 'Clear, respectful interest with no pressure. They express desire while respecting your availability.',
        category: 'healthy',
      },
      {
        id: 'ds_3',
        text: '"If you really loved me, you wouldn\'t need time with your friends."',
        speaker: 'Partner',
        context: 'You mentioned plans with friends',
        isRedFlag: true,
        explanation: 'Conditional love + isolation attempt. Healthy partners support your other relationships, not threaten withdrawal over them.',
        category: 'control',
      },
      {
        id: 'ds_4',
        text: '"I want you to meet my friends, but only when you\'re ready. No pressure."',
        speaker: 'Partner',
        context: 'A month into dating',
        isRedFlag: false,
        explanation: 'Shows investment in integrating you while respecting your pace. Healthy boundary awareness.',
        category: 'healthy',
      },
      {
        id: 'ds_5',
        text: '"I checked your phone while you were sleeping. I just need to make sure you\'re not hiding anything."',
        speaker: 'Partner',
        context: 'Morning conversation',
        isRedFlag: true,
        explanation: 'Privacy violation justified as care. Trust is built through communication, not surveillance.',
        category: 'control',
      },
      {
        id: 'ds_6',
        text: '"I was wrong about that and I\'m sorry. I\'ll do better."',
        speaker: 'Partner',
        context: 'After a disagreement',
        isRedFlag: false,
        explanation: 'Genuine accountability — admits fault, apologizes, and commits to change. This is emotional maturity in action.',
        category: 'healthy',
      },
      {
        id: 'ds_7',
        text: '"My ex was crazy. All my exes were crazy actually."',
        speaker: 'Date',
        context: 'First date conversation',
        isRedFlag: true,
        explanation: 'Pattern of blaming all past partners suggests inability to self-reflect. The common denominator in all their relationships is them.',
        category: 'manipulation',
      },
      {
        id: 'ds_8',
        text: '"I noticed you seemed quiet tonight. Is everything okay, or do you need some space?"',
        speaker: 'Partner',
        context: 'After a social event',
        isRedFlag: false,
        explanation: 'Emotional attunement + offering options. They noticed a change and gave you autonomy in how to respond.',
        category: 'empathetic',
      },
      {
        id: 'ds_9',
        text: '"You\'re making a big deal out of nothing. You\'re so sensitive."',
        speaker: 'Partner',
        context: 'You expressed hurt about something they said',
        isRedFlag: true,
        explanation: 'Classic invalidation/gaslighting. Dismissing your feelings as overreactions teaches you not to trust your own emotional responses.',
        category: 'gaslighting',
      },
      {
        id: 'ds_10',
        text: '"I disagree with you, but I want to understand your perspective. Can you tell me more?"',
        speaker: 'Partner',
        context: 'During a discussion about values',
        isRedFlag: false,
        explanation: 'Disagreement + curiosity is incredibly healthy. They can hold their own view while genuinely wanting to understand yours.',
        category: 'empathetic',
      },
      {
        id: 'ds_11',
        text: '"I don\'t want you wearing that. Other people will look at you."',
        speaker: 'Partner',
        context: 'Getting ready to go out',
        isRedFlag: true,
        explanation: 'Controlling behavior disguised as protectiveness. Your clothing choices are yours. Jealousy-driven control escalates.',
        category: 'control',
      },
      {
        id: 'ds_12',
        text: '"I\'m not ready for that yet, and I hope you can understand."',
        speaker: 'Partner',
        context: 'Discussion about physical intimacy',
        isRedFlag: false,
        explanation: 'Clear boundary + respectful communication. They state their need without guilt or apology.',
        category: 'assertive',
      },
      {
        id: 'ds_13',
        text: '"That never happened. You\'re remembering it wrong. Are you sure you\'re okay?"',
        speaker: 'Partner',
        context: 'You brought up something hurtful they said last week',
        isRedFlag: true,
        explanation: 'Gaslighting — denying reality and questioning your mental state. This erodes your confidence in your own memory and perception.',
        category: 'gaslighting',
      },
      {
        id: 'ds_14',
        text: '"I messed up and I want to fix it. What would make this right for you?"',
        speaker: 'Partner',
        context: 'After they forgot an important date',
        isRedFlag: false,
        explanation: 'Accountability + repair orientation. They own the mistake and center your needs in the resolution.',
        category: 'healthy',
      },
      {
        id: 'ds_15',
        text: '"Nobody else will ever love you the way I do."',
        speaker: 'Partner',
        context: 'During a conversation about the relationship',
        isRedFlag: true,
        explanation: 'Isolation through fear. This statement is designed to make you believe you have no alternatives, keeping you dependent.',
        category: 'manipulation',
      },
    ],
  },
  {
    id: 'workplace_signals',
    title: 'Workplace Red & Green Flags',
    description: 'Distinguish toxic management from healthy leadership',
    difficulty: 2,
    statements: [
      {
        id: 'ws_1',
        text: '"You should feel grateful to work here. Most people would kill for this job."',
        speaker: 'Manager',
        context: 'You asked about a raise',
        isRedFlag: true,
        explanation: 'Guilt-deflection. Using gratitude as a weapon to shut down legitimate requests. Healthy managers address compensation directly.',
        category: 'manipulation',
      },
      {
        id: 'ws_2',
        text: '"That\'s a good point. I hadn\'t thought of it that way. Let me reconsider."',
        speaker: 'Manager',
        context: 'You pushed back on a decision',
        isRedFlag: false,
        explanation: 'Intellectual humility and openness to feedback. This manager values truth over ego.',
        category: 'healthy',
      },
      {
        id: 'ws_3',
        text: '"If you can\'t handle the pressure, maybe this isn\'t the right place for you."',
        speaker: 'Manager',
        context: 'You mentioned burnout',
        isRedFlag: true,
        explanation: 'Threat disguised as a suggestion. Instead of addressing workload, they question your fitness. This silences future concerns.',
        category: 'boundary_violation',
      },
      {
        id: 'ws_4',
        text: '"I want to make sure you have what you need to succeed. What support would help?"',
        speaker: 'Manager',
        context: 'After a missed deadline',
        isRedFlag: false,
        explanation: 'Support-focused leadership. Rather than blame, they look for systemic solutions and ask what you need.',
        category: 'empathetic',
      },
      {
        id: 'ws_5',
        text: '"Don\'t tell anyone about this conversation. It stays between us."',
        speaker: 'Manager',
        context: 'After giving you special treatment',
        isRedFlag: true,
        explanation: 'Secrecy creates power imbalance. If it can\'t be shared, it shouldn\'t be happening. This builds dependency and isolation.',
        category: 'manipulation',
      },
      {
        id: 'ws_6',
        text: '"I made a mistake on that project and I want to own it publicly so the team learns from it."',
        speaker: 'Manager',
        context: 'Team meeting after a setback',
        isRedFlag: false,
        explanation: 'Modeling accountability from the top. This creates psychological safety for the entire team to take healthy risks.',
        category: 'healthy',
      },
      {
        id: 'ws_7',
        text: '"I noticed you\'ve been working late all week. I\'m moving your deadline to give you breathing room."',
        speaker: 'Manager',
        context: 'Midweek check-in',
        isRedFlag: false,
        explanation: 'Proactive care for employee wellbeing. They noticed without being asked and took action to help.',
        category: 'empathetic',
      },
      {
        id: 'ws_8',
        text: '"You know Sarah got fired for less than what you just did, right?"',
        speaker: 'Manager',
        context: 'After a minor mistake',
        isRedFlag: true,
        explanation: 'Implicit threat using a third party as example. Fear-based management creates compliance, not engagement.',
        category: 'manipulation',
      },
      {
        id: 'ws_9',
        text: '"I\'d like to give you honest feedback because I want you to grow here. Is now a good time?"',
        speaker: 'Manager',
        context: 'After a presentation',
        isRedFlag: false,
        explanation: 'Consent-based feedback. They state positive intent and check your readiness. This respects your autonomy.',
        category: 'assertive',
      },
      {
        id: 'ws_10',
        text: '"We\'re a family here. Real family members don\'t watch the clock."',
        speaker: 'Manager',
        context: 'You left at 5pm on a Friday',
        isRedFlag: true,
        explanation: '"Family" framing is used to extract unpaid labor through guilt. Real families don\'t exploit each other.',
        category: 'boundary_violation',
      },
      {
        id: 'ws_11',
        text: '"I disagree with your approach, but I trust your judgment. Go ahead and I\'ll back you up."',
        speaker: 'Manager',
        context: 'Project planning discussion',
        isRedFlag: false,
        explanation: 'Empowerment through trust. They express their view but let you lead and commit to support. This builds confidence.',
        category: 'healthy',
      },
      {
        id: 'ws_12',
        text: '"I\'m going to CC my manager on this email so there\'s no misunderstanding later."',
        speaker: 'Colleague',
        context: 'After a normal work conversation',
        isRedFlag: true,
        explanation: 'Passive-aggressive CYA behavior that signals distrust and creates an adversarial paper trail unnecessarily.',
        category: 'manipulation',
      },
      {
        id: 'ws_13',
        text: '"Let me know if you need anything from me to hit your goals. I\'m here to remove blockers."',
        speaker: 'Manager',
        context: 'Weekly 1-on-1',
        isRedFlag: false,
        explanation: 'Servant leadership — manager sees their role as enabling your success rather than just evaluating it.',
        category: 'healthy',
      },
      {
        id: 'ws_14',
        text: '"I\'m disappointed in you. I thought you were better than this."',
        speaker: 'Manager',
        context: 'Performance conversation',
        isRedFlag: true,
        explanation: 'Identity attack disguised as disappointment. Criticizes who you are rather than what you did. Healthy feedback is specific and behavioral.',
        category: 'manipulation',
      },
      {
        id: 'ws_15',
        text: '"Your work-life balance matters to me. Please don\'t answer emails after 7pm."',
        speaker: 'Manager',
        context: 'Onboarding conversation',
        isRedFlag: false,
        explanation: 'Proactive boundary-setting from leadership. This gives explicit permission to disconnect and models healthy norms.',
        category: 'assertive',
      },
    ],
  },
  {
    id: 'friendship_signals',
    title: 'Friendship Check',
    description: 'Recognize healthy vs toxic patterns in friendships',
    difficulty: 2,
    statements: [
      {
        id: 'fs_1',
        text: '"I need you right now. Drop whatever you\'re doing."',
        speaker: 'Friend',
        context: 'They want to vent about a non-emergency',
        isRedFlag: true,
        explanation: 'Demanding immediate availability for non-emergencies shows disregard for your time and boundaries.',
        category: 'boundary_violation',
      },
      {
        id: 'fs_2',
        text: '"I know you\'re busy. Just text me when you have a minute — no rush."',
        speaker: 'Friend',
        context: 'They want to catch up',
        isRedFlag: false,
        explanation: 'Respects your time while expressing desire to connect. No pressure, no guilt.',
        category: 'healthy',
      },
      {
        id: 'fs_3',
        text: '"You\'ve changed. You think you\'re better than us now."',
        speaker: 'Friend',
        context: 'You got a promotion and have less free time',
        isRedFlag: true,
        explanation: 'Punishing growth. Healthy friends celebrate your success; toxic friends treat it as betrayal.',
        category: 'manipulation',
      },
      {
        id: 'fs_4',
        text: '"I\'m so proud of you. You deserve this."',
        speaker: 'Friend',
        context: 'After your achievement',
        isRedFlag: false,
        explanation: 'Genuine celebration without jealousy or conditions. They center your joy.',
        category: 'healthy',
      },
      {
        id: 'fs_5',
        text: '"I told everyone about your breakup. I was just worried about you."',
        speaker: 'Friend',
        context: 'You confided something personal',
        isRedFlag: true,
        explanation: 'Betraying confidence and justifying it as concern. "Worry" doesn\'t override your right to privacy.',
        category: 'boundary_violation',
      },
      {
        id: 'fs_6',
        text: '"I was wrong to say that. I\'m sorry — can I make it up to you?"',
        speaker: 'Friend',
        context: 'After saying something hurtful',
        isRedFlag: false,
        explanation: 'Clean apology: acknowledgment + responsibility + repair offer. No excuses, no "but."',
        category: 'healthy',
      },
      {
        id: 'fs_7',
        text: '"If you don\'t come to my party, I\'ll know where I stand with you."',
        speaker: 'Friend',
        context: 'You have a scheduling conflict',
        isRedFlag: true,
        explanation: 'Emotional ultimatum that equates one event with the entire friendship. Manipulative loyalty test.',
        category: 'manipulation',
      },
      {
        id: 'fs_8',
        text: '"I don\'t agree with your decision, but I support you and I\'m here if you need me."',
        speaker: 'Friend',
        context: 'You\'re making a life change they\'re unsure about',
        isRedFlag: false,
        explanation: 'Honest disagreement paired with unconditional support. They respect your autonomy while being truthful.',
        category: 'assertive',
      },
      {
        id: 'fs_9',
        text: '"Remember when I helped you move? You owe me."',
        speaker: 'Friend',
        context: 'Asking you to do them a big favor',
        isRedFlag: true,
        explanation: 'Scorecard keeping. Using past favors as leverage turns friendship into a transaction.',
        category: 'manipulation',
      },
      {
        id: 'fs_10',
        text: '"That must be really hard. I don\'t fully understand, but I\'m listening."',
        speaker: 'Friend',
        context: 'You\'re going through something difficult',
        isRedFlag: false,
        explanation: 'Honest empathy — they acknowledge their limits while staying present. More valuable than pretending to understand.',
        category: 'empathetic',
      },
      {
        id: 'fs_11',
        text: '"Everyone thinks you\'re being selfish, not just me."',
        speaker: 'Friend',
        context: 'Disagreement about plans',
        isRedFlag: true,
        explanation: 'Triangulation — invoking unnamed others to amplify pressure and make you doubt yourself.',
        category: 'gaslighting',
      },
      {
        id: 'fs_12',
        text: '"I miss hanging out. Want to find a time that works for both of us?"',
        speaker: 'Friend',
        context: 'You\'ve both been busy',
        isRedFlag: false,
        explanation: 'Expresses need + collaborative solution. No guilt, no accusation, just genuine connection-seeking.',
        category: 'healthy',
      },
      {
        id: 'fs_13',
        text: '"I can\'t believe you\'re hanging out with them. They\'re awful people."',
        speaker: 'Friend',
        context: 'You mention plans with other friends',
        isRedFlag: true,
        explanation: 'Attempting to control your social circle by badmouthing others. Healthy friends don\'t gatekeep your relationships.',
        category: 'control',
      },
      {
        id: 'fs_14',
        text: '"I need to set a boundary — I can\'t be your emotional support right now, but I care about you."',
        speaker: 'Friend',
        context: 'During a particularly draining period',
        isRedFlag: false,
        explanation: 'Modeling healthy limits. They protect their energy while affirming the relationship. This is self-care, not abandonment.',
        category: 'assertive',
      },
      {
        id: 'fs_15',
        text: '"Fine, go. Everyone always leaves eventually."',
        speaker: 'Friend',
        context: 'You need to leave a hangout early',
        isRedFlag: true,
        explanation: 'Victim narrative to induce guilt. Framing normal departures as abandonment is emotionally manipulative.',
        category: 'manipulation',
      },
    ],
  },
];

export const ADVANCED_FLAG_SETS: RedFlagSet[] = [
  {
    id: 'family_patterns',
    title: 'Family Pattern Check',
    description: 'Spot enmeshment, parentification, and toxic family dynamics',
    difficulty: 3,
    statements: [
      {
        id: 'fp_1',
        text: '"You\'re the only one I can really talk to about this. Don\'t tell your father."',
        speaker: 'Mother',
        context: 'She confides adult relationship problems to you regularly',
        isRedFlag: true,
        explanation: 'Parentification — using a child as an emotional confidant for adult problems. Creates loyalty binds and role confusion. Parents should seek peer or professional support.',
        category: 'boundary_violation',
      },
      {
        id: 'fp_2',
        text: '"I disagree with your decision, but I trust you. Let me know if you need anything."',
        speaker: 'Parent',
        context: 'You made a life choice they wouldn\'t have made',
        isRedFlag: false,
        explanation: 'Healthy differentiation — they separate their feelings from your autonomy. Expressing disagreement while maintaining support is emotional maturity.',
        category: 'healthy',
      },
      {
        id: 'fp_3',
        text: '"If you move away, it will kill your grandmother. You know she can\'t handle that."',
        speaker: 'Parent',
        context: 'You\'re considering a job opportunity in another city',
        isRedFlag: true,
        explanation: 'Weaponizing a third party\'s health/emotions to control your decisions. Your grandmother\'s wellbeing is not your career decision to make. This is triangulation through guilt.',
        category: 'manipulation',
      },
      {
        id: 'fp_4',
        text: '"I\'m proud of who you\'re becoming, even though it\'s different from what I imagined."',
        speaker: 'Parent',
        context: 'Your career path differs from their expectations',
        isRedFlag: false,
        explanation: 'Vulnerability + acceptance. Admitting they had a different picture while choosing pride anyway shows genuine love that adapts rather than controls.',
        category: 'healthy',
      },
      {
        id: 'fp_5',
        text: '"We don\'t air our dirty laundry. What happens in this family stays in this family."',
        speaker: 'Parent',
        context: 'You mentioned going to therapy',
        isRedFlag: true,
        explanation: 'Enforced secrecy protects dysfunction, not people. Healthy families encourage support-seeking. This rule keeps problems hidden and members isolated.',
        category: 'control',
      },
      {
        id: 'fp_6',
        text: '"I know I wasn\'t perfect as a parent. I\'m working on understanding how that affected you."',
        speaker: 'Parent',
        context: 'Conversation about childhood experiences',
        isRedFlag: false,
        explanation: 'Accountability without defensiveness. Acknowledging imperfection and actively working to understand impact is the foundation of healing.',
        category: 'healthy',
      },
      {
        id: 'fp_7',
        text: '"You owe me. I gave up my career to raise you."',
        speaker: 'Parent',
        context: 'You declined to lend them a significant amount of money',
        isRedFlag: true,
        explanation: 'Transactional parenting — treating childrearing as a debt to be repaid. Parenting is a choice, not an invoice. This creates lifelong obligation.',
        category: 'manipulation',
      },
      {
        id: 'fp_8',
        text: '"Your boundaries are hard for me, but I\'m trying to respect them."',
        speaker: 'Parent',
        context: 'After you set limits on unannounced visits',
        isRedFlag: false,
        explanation: 'Honest struggle + genuine effort. They\'re not weaponizing their discomfort — they\'re naming it while choosing respect. Growth looks uncomfortable.',
        category: 'healthy',
      },
      {
        id: 'fp_9',
        text: '"I guess I\'m just a terrible mother then. Is that what you\'re saying?"',
        speaker: 'Mother',
        context: 'You expressed that something she did hurt you',
        isRedFlag: true,
        explanation: 'DARVO in action — Deny, Attack, Reverse Victim and Offender. Your feedback about a specific hurt gets flipped into an accusation against you. Now you\'re comforting her instead of being heard.',
        category: 'gaslighting',
      },
      {
        id: 'fp_10',
        text: '"I don\'t have to agree with your lifestyle to love you unconditionally."',
        speaker: 'Parent',
        context: 'Discussing a life choice they struggle with',
        isRedFlag: false,
        explanation: 'Separating love from agreement. While "lifestyle" framing can be loaded, the core message — love without conditions — demonstrates that acceptance doesn\'t require endorsement.',
        category: 'healthy',
      },
      {
        id: 'fp_11',
        text: '"Your sister would never treat me like this."',
        speaker: 'Parent',
        context: 'You set a boundary about holiday plans',
        isRedFlag: true,
        explanation: 'Sibling comparison as punishment. Designed to trigger shame and competition. The boundary you set is healthy — the comparison is a deflection from addressing it.',
        category: 'manipulation',
      },
      {
        id: 'fp_12',
        text: '"I want to hear your side. I may have been wrong about how I handled that."',
        speaker: 'Parent',
        context: 'Revisiting an old family conflict',
        isRedFlag: false,
        explanation: 'Openness to being wrong is rare and powerful. Inviting your perspective shows they value truth over being right. This creates genuine repair.',
        category: 'empathetic',
      },
      {
        id: 'fp_13',
        text: '"After the divorce, you\'re the man of the house now. I\'m counting on you."',
        speaker: 'Mother',
        context: 'Said to a 12-year-old son',
        isRedFlag: true,
        explanation: 'Parentification — burdening a child with adult responsibility and emotional weight. Children need to be children, not surrogate partners or protectors.',
        category: 'boundary_violation',
      },
      {
        id: 'fp_14',
        text: '"I can see you\'re going through a lot. You don\'t need to take care of me right now."',
        speaker: 'Parent',
        context: 'You\'re dealing with your own crisis and they noticed you checking on them',
        isRedFlag: false,
        explanation: 'Releasing you from caretaking obligations during your own hardship. This parent prioritizes your wellbeing over their need for attention. Genuine selflessness.',
        category: 'empathetic',
      },
      {
        id: 'fp_15',
        text: '"You\'re too sensitive. We\'re family — I should be able to say anything to you."',
        speaker: 'Family member',
        context: 'You asked them to stop making hurtful jokes',
        isRedFlag: true,
        explanation: 'Using "family" as a license to bypass boundaries. Closeness should increase care, not decrease it. "Too sensitive" invalidates your legitimate feelings.',
        category: 'gaslighting',
      },
    ],
  },
  {
    id: 'digital_signals',
    title: 'Digital & Social Media Flags',
    description: 'Identify manipulation, healthy behavior, and red flags in online interactions',
    difficulty: 2,
    statements: [
      {
        id: 'dg_1',
        text: '"Why aren\'t you answering? I can see you\'re online." (3 messages in 5 minutes)',
        speaker: 'Someone you\'re dating',
        context: 'You were busy at work and didn\'t respond immediately',
        isRedFlag: true,
        explanation: 'Monitoring online status and demanding instant responses is digital surveillance. It signals possessiveness and escalates — today it\'s texts, tomorrow it\'s location tracking.',
        category: 'control',
      },
      {
        id: 'dg_2',
        text: '"No rush on replying — I know you\'re busy today. Just wanted to share this with you."',
        speaker: 'Friend',
        context: 'They sent you an article they thought you\'d enjoy',
        isRedFlag: false,
        explanation: 'Low-pressure sharing. They thought of you, wanted to connect, but explicitly removed any urgency. This is thoughtful digital communication.',
        category: 'healthy',
      },
      {
        id: 'dg_3',
        text: '"Who is this person liking all your photos? Should I be worried?"',
        speaker: 'Partner',
        context: 'A colleague interacted with a few of your social media posts',
        isRedFlag: true,
        explanation: 'Social media surveillance disguised as concern. Monitoring who interacts with your posts and interrogating you about it crosses into controlling territory.',
        category: 'control',
      },
      {
        id: 'dg_4',
        text: '"I saw you had a rough day from your post. Want to talk about it, or do you need space?"',
        speaker: 'Close friend',
        context: 'You posted something vague about a bad day',
        isRedFlag: false,
        explanation: 'Noticed and reached out privately with options. They didn\'t make it public, didn\'t pressure, and offered both connection and space. Quality friendship.',
        category: 'empathetic',
      },
      {
        id: 'dg_5',
        text: '"Delete that photo. I don\'t want people seeing you look like that."',
        speaker: 'Partner',
        context: 'You posted a normal photo at a social event',
        isRedFlag: true,
        explanation: 'Controlling your self-expression and public image. Your social media presence is yours to manage. Dictating what you can post is a control tactic.',
        category: 'control',
      },
      {
        id: 'dg_6',
        text: '"I\'m putting my phone away so we can actually be present together tonight."',
        speaker: 'Partner',
        context: 'Date night',
        isRedFlag: false,
        explanation: 'Voluntary digital boundaries for quality connection. They\'re choosing presence over distraction without demanding you do the same.',
        category: 'healthy',
      },
      {
        id: 'dg_7',
        text: '"Give me your phone password. If you have nothing to hide, it shouldn\'t be a problem."',
        speaker: 'Partner',
        context: 'Early in the relationship — no trust issues have occurred',
        isRedFlag: true,
        explanation: 'The "nothing to hide" argument is a manipulation classic. Privacy is a right, not evidence of guilt. This demand establishes surveillance as the norm.',
        category: 'control',
      },
      {
        id: 'dg_8',
        text: '"I\'m not great at texting but I want you to know I\'m thinking of you. Coffee this week?"',
        speaker: 'Friend',
        context: 'You haven\'t heard from them in a while',
        isRedFlag: false,
        explanation: 'Self-aware about limitations + concrete action to connect. They don\'t promise to change their texting habits — they offer something real instead.',
        category: 'assertive',
      },
      {
        id: 'dg_9',
        text: '"I posted that photo of us without asking. Want me to take it down?"',
        speaker: 'Friend',
        context: 'They posted a group photo from last weekend',
        isRedFlag: false,
        explanation: 'Recognizing they should have asked + offering to fix it. Post-action consent isn\'t ideal, but the awareness and offer to remove shows respect.',
        category: 'healthy',
      },
      {
        id: 'dg_10',
        text: '"I created a fake account to check if you\'re talking to other people."',
        speaker: 'Partner',
        context: 'They confess to catfishing you as a "trust test"',
        isRedFlag: true,
        explanation: 'Deception to test loyalty. Creating fake accounts is predatory surveillance. The irony: they broke trust to "test" yours. This is a serious boundary violation.',
        category: 'manipulation',
      },
      {
        id: 'dg_11',
        text: '"Hey, I vented about our argument in a group chat and I shouldn\'t have. I\'m sorry."',
        speaker: 'Friend',
        context: 'They took a conflict public then realized it was wrong',
        isRedFlag: false,
        explanation: 'Unprompted accountability for a digital boundary violation. They identified the problem, owned it, and apologized before you even found out. This is integrity.',
        category: 'healthy',
      },
      {
        id: 'dg_12',
        text: '"I screenshotted your private messages and shared them with people."',
        speaker: 'Ex-friend',
        context: 'After a falling out, they weaponized your private conversations',
        isRedFlag: true,
        explanation: 'Digital betrayal — using private communication as ammunition. This weaponizes vulnerability and makes future trust extremely difficult.',
        category: 'boundary_violation',
      },
      {
        id: 'dg_13',
        text: '"I noticed you unfollowed me. Did I do something wrong, or do you just need space?"',
        speaker: 'Acquaintance',
        context: 'You curated your social media feed',
        isRedFlag: false,
        explanation: 'Direct communication instead of passive speculation. Asking openly shows maturity — they\'re checking in rather than assuming the worst or retaliating.',
        category: 'assertive',
      },
      {
        id: 'dg_14',
        text: '"I\'m going to post our private argument on social media so everyone can see who\'s right."',
        speaker: 'Partner',
        context: 'Unresolved disagreement',
        isRedFlag: true,
        explanation: 'Threatening public humiliation to "win." Using an audience as a weapon turns your relationship into a courtroom. Healthy conflict stays private.',
        category: 'manipulation',
      },
      {
        id: 'dg_15',
        text: '"I unfollowed some accounts that were making me feel bad about myself. Nothing to do with you."',
        speaker: 'Partner',
        context: 'They curated their social media for mental health',
        isRedFlag: false,
        explanation: 'Healthy digital self-care + proactive transparency. They made a personal decision and communicated it clearly so you wouldn\'t misinterpret.',
        category: 'healthy',
      },
    ],
  },
];

RED_FLAG_SETS.push(...ADVANCED_FLAG_SETS);

export function getRedFlagSetById(id: string): RedFlagSet | undefined {
  return RED_FLAG_SETS.find((s) => s.id === id);
}
