export interface RedFlagSet {
  id: string;
  title: string;
  description: string;
  difficulty: number;
  statements: FlagStatement[];
}

export interface FlagStatement {
  id: string;
  text: string;
  speaker: string;
  context: string;
  isRedFlag: boolean;
  explanation: string;
  category: 'manipulation' | 'boundary_violation' | 'gaslighting' | 'love_bombing' | 'control' | 'healthy' | 'assertive' | 'empathetic';
}

export const RED_FLAG_SETS: RedFlagSet[] = [
  {
    id: 'dating_signals',
    title: 'Dating Red & Green Flags',
    description: 'Spot the warning signs and healthy behaviors in early dating',
    difficulty: 1,
    statements: [
      {
        id: 'ds_1',
        text: '"I\'ve never felt this way about anyone. You\'re my soulmate and we\'ve only been dating two weeks."',
        speaker: 'New partner',
        context: 'Second week of dating',
        isRedFlag: true,
        explanation: 'Love bombing — excessive intensity too early is a manipulation tactic, not genuine connection. Healthy relationships build gradually.',
        category: 'love_bombing',
      },
      {
        id: 'ds_2',
        text: '"I had a great time tonight. I\'d love to see you again this weekend if you\'re free."',
        speaker: 'Date',
        context: 'End of a third date',
        isRedFlag: false,
        explanation: 'Clear, respectful interest with no pressure. They express desire while respecting your availability.',
        category: 'healthy',
      },
      {
        id: 'ds_3',
        text: '"If you really loved me, you wouldn\'t need time with your friends."',
        speaker: 'Partner',
        context: 'You mentioned plans with friends',
        isRedFlag: true,
        explanation: 'Conditional love + isolation attempt. Healthy partners support your other relationships, not threaten withdrawal over them.',
        category: 'control',
      },
      {
        id: 'ds_4',
        text: '"I want you to meet my friends, but only when you\'re ready. No pressure."',
        speaker: 'Partner',
        context: 'A month into dating',
        isRedFlag: false,
        explanation: 'Shows investment in integrating you while respecting your pace. Healthy boundary awareness.',
        category: 'healthy',
      },
      {
        id: 'ds_5',
        text: '"I checked your phone while you were sleeping. I just need to make sure you\'re not hiding anything."',
        speaker: 'Partner',
        context: 'Morning conversation',
        isRedFlag: true,
        explanation: 'Privacy violation justified as care. Trust is built through communication, not surveillance.',
        category: 'control',
      },
      {
        id: 'ds_6',
        text: '"I was wrong about that and I\'m sorry. I\'ll do better."',
        speaker: 'Partner',
        context: 'After a disagreement',
        isRedFlag: false,
        explanation: 'Genuine accountability — admits fault, apologizes, and commits to change. This is emotional maturity in action.',
        category: 'healthy',
      },
      {
        id: 'ds_7',
        text: '"My ex was crazy. All my exes were crazy actually."',
        speaker: 'Date',
        context: 'First date conversation',
        isRedFlag: true,
        explanation: 'Pattern of blaming all past partners suggests inability to self-reflect. The common denominator in all their relationships is them.',
        category: 'manipulation',
      },
      {
        id: 'ds_8',
        text: '"I noticed you seemed quiet tonight. Is everything okay, or do you need some space?"',
        speaker: 'Partner',
        context: 'After a social event',
        isRedFlag: false,
        explanation: 'Emotional attunement + offering options. They noticed a change and gave you autonomy in how to respond.',
        category: 'empathetic',
      },
      {
        id: 'ds_9',
        text: '"You\'re making a big deal out of nothing. You\'re so sensitive."',
        speaker: 'Partner',
        context: 'You expressed hurt about something they said',
        isRedFlag: true,
        explanation: 'Classic invalidation/gaslighting. Dismissing your feelings as overreactions teaches you not to trust your own emotional responses.',
        category: 'gaslighting',
      },
      {
        id: 'ds_10',
        text: '"I disagree with you, but I want to understand your perspective. Can you tell me more?"',
        speaker: 'Partner',
        context: 'During a discussion about values',
        isRedFlag: false,
        explanation: 'Disagreement + curiosity is incredibly healthy. They can hold their own view while genuinely wanting to understand yours.',
        category: 'empathetic',
      },
      {
        id: 'ds_11',
        text: '"I don\'t want you wearing that. Other people will look at you."',
        speaker: 'Partner',
        context: 'Getting ready to go out',
        isRedFlag: true,
        explanation: 'Controlling behavior disguised as protectiveness. Your clothing choices are yours. Jealousy-driven control escalates.',
        category: 'control',
      },
      {
        id: 'ds_12',
        text: '"I\'m not ready for that yet, and I hope you can understand."',
        speaker: 'Partner',
        context: 'Discussion about physical intimacy',
        isRedFlag: false,
        explanation: 'Clear boundary + respectful communication. They state their need without guilt or apology.',
        category: 'assertive',
      },
      {
        id: 'ds_13',
        text: '"That never happened. You\'re remembering it wrong. Are you sure you\'re okay?"',
        speaker: 'Partner',
        context: 'You brought up something hurtful they said last week',
        isRedFlag: true,
        explanation: 'Gaslighting — denying reality and questioning your mental state. This erodes your confidence in your own memory and perception.',
        category: 'gaslighting',
      },
      {
        id: 'ds_14',
        text: '"I messed up and I want to fix it. What would make this right for you?"',
        speaker: 'Partner',
        context: 'After they forgot an important date',
        isRedFlag: false,
        explanation: 'Accountability + repair orientation. They own the mistake and center your needs in the resolution.',
        category: 'healthy',
      },
      {
        id: 'ds_15',
        text: '"Nobody else will ever love you the way I do."',
        speaker: 'Partner',
        context: 'During a conversation about the relationship',
        isRedFlag: true,
        explanation: 'Isolation through fear. This statement is designed to make you believe you have no alternatives, keeping you dependent.',
        category: 'manipulation',
      },
    ],
  },
  {
    id: 'workplace_signals',
    title: 'Workplace Red & Green Flags',
    description: 'Distinguish toxic management from healthy leadership',
    difficulty: 2,
    statements: [
      {
        id: 'ws_1',
        text: '"You should feel grateful to work here. Most people would kill for this job."',
        speaker: 'Manager',
        context: 'You asked about a raise',
        isRedFlag: true,
        explanation: 'Guilt-deflection. Using gratitude as a weapon to shut down legitimate requests. Healthy managers address compensation directly.',
        category: 'manipulation',
      },
      {
        id: 'ws_2',
        text: '"That\'s a good point. I hadn\'t thought of it that way. Let me reconsider."',
        speaker: 'Manager',
        context: 'You pushed back on a decision',
        isRedFlag: false,
        explanation: 'Intellectual humility and openness to feedback. This manager values truth over ego.',
        category: 'healthy',
      },
      {
        id: 'ws_3',
        text: '"If you can\'t handle the pressure, maybe this isn\'t the right place for you."',
        speaker: 'Manager',
        context: 'You mentioned burnout',
        isRedFlag: true,
        explanation: 'Threat disguised as a suggestion. Instead of addressing workload, they question your fitness. This silences future concerns.',
        category: 'boundary_violation',
      },
      {
        id: 'ws_4',
        text: '"I want to make sure you have what you need to succeed. What support would help?"',
        speaker: 'Manager',
        context: 'After a missed deadline',
        isRedFlag: false,
        explanation: 'Support-focused leadership. Rather than blame, they look for systemic solutions and ask what you need.',
        category: 'empathetic',
      },
      {
        id: 'ws_5',
        text: '"Don\'t tell anyone about this conversation. It stays between us."',
        speaker: 'Manager',
        context: 'After giving you special treatment',
        isRedFlag: true,
        explanation: 'Secrecy creates power imbalance. If it can\'t be shared, it shouldn\'t be happening. This builds dependency and isolation.',
        category: 'manipulation',
      },
      {
        id: 'ws_6',
        text: '"I made a mistake on that project and I want to own it publicly so the team learns from it."',
        speaker: 'Manager',
        context: 'Team meeting after a setback',
        isRedFlag: false,
        explanation: 'Modeling accountability from the top. This creates psychological safety for the entire team to take healthy risks.',
        category: 'healthy',
      },
      {
        id: 'ws_7',
        text: '"I noticed you\'ve been working late all week. I\'m moving your deadline to give you breathing room."',
        speaker: 'Manager',
        context: 'Midweek check-in',
        isRedFlag: false,
        explanation: 'Proactive care for employee wellbeing. They noticed without being asked and took action to help.',
        category: 'empathetic',
      },
      {
        id: 'ws_8',
        text: '"You know Sarah got fired for less than what you just did, right?"',
        speaker: 'Manager',
        context: 'After a minor mistake',
        isRedFlag: true,
        explanation: 'Implicit threat using a third party as example. Fear-based management creates compliance, not engagement.',
        category: 'manipulation',
      },
      {
        id: 'ws_9',
        text: '"I\'d like to give you honest feedback because I want you to grow here. Is now a good time?"',
        speaker: 'Manager',
        context: 'After a presentation',
        isRedFlag: false,
        explanation: 'Consent-based feedback. They state positive intent and check your readiness. This respects your autonomy.',
        category: 'assertive',
      },
      {
        id: 'ws_10',
        text: '"We\'re a family here. Real family members don\'t watch the clock."',
        speaker: 'Manager',
        context: 'You left at 5pm on a Friday',
        isRedFlag: true,
        explanation: '"Family" framing is used to extract unpaid labor through guilt. Real families don\'t exploit each other.',
        category: 'boundary_violation',
      },
      {
        id: 'ws_11',
        text: '"I disagree with your approach, but I trust your judgment. Go ahead and I\'ll back you up."',
        speaker: 'Manager',
        context: 'Project planning discussion',
        isRedFlag: false,
        explanation: 'Empowerment through trust. They express their view but let you lead and commit to support. This builds confidence.',
        category: 'healthy',
      },
      {
        id: 'ws_12',
        text: '"I\'m going to CC my manager on this email so there\'s no misunderstanding later."',
        speaker: 'Colleague',
        context: 'After a normal work conversation',
        isRedFlag: true,
        explanation: 'Passive-aggressive CYA behavior that signals distrust and creates an adversarial paper trail unnecessarily.',
        category: 'manipulation',
      },
      {
        id: 'ws_13',
        text: '"Let me know if you need anything from me to hit your goals. I\'m here to remove blockers."',
        speaker: 'Manager',
        context: 'Weekly 1-on-1',
        isRedFlag: false,
        explanation: 'Servant leadership — manager sees their role as enabling your success rather than just evaluating it.',
        category: 'healthy',
      },
      {
        id: 'ws_14',
        text: '"I\'m disappointed in you. I thought you were better than this."',
        speaker: 'Manager',
        context: 'Performance conversation',
        isRedFlag: true,
        explanation: 'Identity attack disguised as disappointment. Criticizes who you are rather than what you did. Healthy feedback is specific and behavioral.',
        category: 'manipulation',
      },
      {
        id: 'ws_15',
        text: '"Your work-life balance matters to me. Please don\'t answer emails after 7pm."',
        speaker: 'Manager',
        context: 'Onboarding conversation',
        isRedFlag: false,
        explanation: 'Proactive boundary-setting from leadership. This gives explicit permission to disconnect and models healthy norms.',
        category: 'assertive',
      },
    ],
  },
  {
    id: 'friendship_signals',
    title: 'Friendship Check',
    description: 'Recognize healthy vs toxic patterns in friendships',
    difficulty: 2,
    statements: [
      {
        id: 'fs_1',
        text: '"I need you right now. Drop whatever you\'re doing."',
        speaker: 'Friend',
        context: 'They want to vent about a non-emergency',
        isRedFlag: true,
        explanation: 'Demanding immediate availability for non-emergencies shows disregard for your time and boundaries.',
        category: 'boundary_violation',
      },
      {
        id: 'fs_2',
        text: '"I know you\'re busy. Just text me when you have a minute — no rush."',
        speaker: 'Friend',
        context: 'They want to catch up',
        isRedFlag: false,
        explanation: 'Respects your time while expressing desire to connect. No pressure, no guilt.',
        category: 'healthy',
      },
      {
        id: 'fs_3',
        text: '"You\'ve changed. You think you\'re better than us now."',
        speaker: 'Friend',
        context: 'You got a promotion and have less free time',
        isRedFlag: true,
        explanation: 'Punishing growth. Healthy friends celebrate your success; toxic friends treat it as betrayal.',
        category: 'manipulation',
      },
      {
        id: 'fs_4',
        text: '"I\'m so proud of you. You deserve this."',
        speaker: 'Friend',
        context: 'After your achievement',
        isRedFlag: false,
        explanation: 'Genuine celebration without jealousy or conditions. They center your joy.',
        category: 'healthy',
      },
      {
        id: 'fs_5',
        text: '"I told everyone about your breakup. I was just worried about you."',
        speaker: 'Friend',
        context: 'You confided something personal',
        isRedFlag: true,
        explanation: 'Betraying confidence and justifying it as concern. "Worry" doesn\'t override your right to privacy.',
        category: 'boundary_violation',
      },
      {
        id: 'fs_6',
        text: '"I was wrong to say that. I\'m sorry — can I make it up to you?"',
        speaker: 'Friend',
        context: 'After saying something hurtful',
        isRedFlag: false,
        explanation: 'Clean apology: acknowledgment + responsibility + repair offer. No excuses, no "but."',
        category: 'healthy',
      },
      {
        id: 'fs_7',
        text: '"If you don\'t come to my party, I\'ll know where I stand with you."',
        speaker: 'Friend',
        context: 'You have a scheduling conflict',
        isRedFlag: true,
        explanation: 'Emotional ultimatum that equates one event with the entire friendship. Manipulative loyalty test.',
        category: 'manipulation',
      },
      {
        id: 'fs_8',
        text: '"I don\'t agree with your decision, but I support you and I\'m here if you need me."',
        speaker: 'Friend',
        context: 'You\'re making a life change they\'re unsure about',
        isRedFlag: false,
        explanation: 'Honest disagreement paired with unconditional support. They respect your autonomy while being truthful.',
        category: 'assertive',
      },
      {
        id: 'fs_9',
        text: '"Remember when I helped you move? You owe me."',
        speaker: 'Friend',
        context: 'Asking you to do them a big favor',
        isRedFlag: true,
        explanation: 'Scorecard keeping. Using past favors as leverage turns friendship into a transaction.',
        category: 'manipulation',
      },
      {
        id: 'fs_10',
        text: '"That must be really hard. I don\'t fully understand, but I\'m listening."',
        speaker: 'Friend',
        context: 'You\'re going through something difficult',
        isRedFlag: false,
        explanation: 'Honest empathy — they acknowledge their limits while staying present. More valuable than pretending to understand.',
        category: 'empathetic',
      },
      {
        id: 'fs_11',
        text: '"Everyone thinks you\'re being selfish, not just me."',
        speaker: 'Friend',
        context: 'Disagreement about plans',
        isRedFlag: true,
        explanation: 'Triangulation — invoking unnamed others to amplify pressure and make you doubt yourself.',
        category: 'gaslighting',
      },
      {
        id: 'fs_12',
        text: '"I miss hanging out. Want to find a time that works for both of us?"',
        speaker: 'Friend',
        context: 'You\'ve both been busy',
        isRedFlag: false,
        explanation: 'Expresses need + collaborative solution. No guilt, no accusation, just genuine connection-seeking.',
        category: 'healthy',
      },
      {
        id: 'fs_13',
        text: '"I can\'t believe you\'re hanging out with them. They\'re awful people."',
        speaker: 'Friend',
        context: 'You mention plans with other friends',
        isRedFlag: true,
        explanation: 'Attempting to control your social circle by badmouthing others. Healthy friends don\'t gatekeep your relationships.',
        category: 'control',
      },
      {
        id: 'fs_14',
        text: '"I need to set a boundary — I can\'t be your emotional support right now, but I care about you."',
        speaker: 'Friend',
        context: 'During a particularly draining period',
        isRedFlag: false,
        explanation: 'Modeling healthy limits. They protect their energy while affirming the relationship. This is self-care, not abandonment.',
        category: 'assertive',
      },
      {
        id: 'fs_15',
        text: '"Fine, go. Everyone always leaves eventually."',
        speaker: 'Friend',
        context: 'You need to leave a hangout early',
        isRedFlag: true,
        explanation: 'Victim narrative to induce guilt. Framing normal departures as abandonment is emotionally manipulative.',
        category: 'manipulation',
      },
    ],
  },
];

export function getRedFlagSetById(id: string): RedFlagSet | undefined {
  return RED_FLAG_SETS.find((s) => s.id === id);
}
