export interface FlashJudgmentSet {
  id: string;
  title: string;
  description: string;
  difficulty: number;
  questions: FlashQuestion[];
}

export interface FlashQuestion {
  id: string;
  scenario: string;
  context: string;
  options: FlashOption[];
  correctOptionId: string;
  explanation: string;
  skillTrack: string;
}

export interface FlashOption {
  id: string;
  text: string;
  quality: 'best' | 'okay' | 'poor' | 'worst';
}

export const FLASH_JUDGMENT_SETS: FlashJudgmentSet[] = [
  {
    id: 'workplace_basics',
    title: 'Workplace Essentials',
    description: 'Navigate common office conflicts with the best response',
    difficulty: 1,
    questions: [
      {
        id: 'wb_1',
        scenario: 'Your coworker takes credit for your idea in a meeting.',
        context: 'Team meeting with 8 people, your manager is present.',
        options: [
          { id: 'wb_1a', text: '"I appreciate you building on that — I\'d love to walk through the details since I developed the initial concept."', quality: 'best' },
          { id: 'wb_1b', text: '"That was actually MY idea and everyone here knows it."', quality: 'worst' },
          { id: 'wb_1c', text: '"Great point. I had some additional thoughts from when I was working on this earlier..."', quality: 'okay' },
          { id: 'wb_1d', text: 'Say nothing and bring it up with your manager later.', quality: 'poor' },
        ],
        correctOptionId: 'wb_1a',
        explanation: 'Acknowledge the person while clearly establishing ownership. Direct but not aggressive — maintains the relationship while protecting your contribution.',
        skillTrack: 'assert',
      },
      {
        id: 'wb_2',
        scenario: 'Your boss says "We need to talk" with no other context.',
        context: 'Friday afternoon, you haven\'t made any known mistakes recently.',
        options: [
          { id: 'wb_2a', text: 'Immediately start worrying and mentally preparing defenses.', quality: 'worst' },
          { id: 'wb_2b', text: '"Sure, I have time now. What\'s on your mind?"', quality: 'best' },
          { id: 'wb_2c', text: '"Is everything okay? Did I do something wrong?"', quality: 'poor' },
          { id: 'wb_2d', text: '"I\'m available. Want to give me a heads up on the topic so I can prepare?"', quality: 'okay' },
        ],
        correctOptionId: 'wb_2b',
        explanation: 'Stay calm and open. Don\'t assume the worst or pre-apologize — it gives away power and signals anxiety. Meet the moment as it comes.',
        skillTrack: 'regulate',
      },
      {
        id: 'wb_3',
        scenario: 'A colleague constantly interrupts you during discussions.',
        context: 'This has happened in the last 3 meetings. Others have noticed.',
        options: [
          { id: 'wb_3a', text: '"I\'d like to finish my thought — I\'ll make sure you have time to respond after."', quality: 'best' },
          { id: 'wb_3b', text: 'Start interrupting them back to establish dominance.', quality: 'worst' },
          { id: 'wb_3c', text: 'Let them talk and bring it up privately later.', quality: 'okay' },
          { id: 'wb_3d', text: '"Can you please stop interrupting me? It\'s really rude."', quality: 'poor' },
        ],
        correctOptionId: 'wb_3a',
        explanation: 'Firm boundary + collaborative framing. You assert your right to speak while assuring them they\'ll be heard too. No accusation, no doormat.',
        skillTrack: 'assert',
      },
      {
        id: 'wb_4',
        scenario: 'Your teammate misses a deadline that affects your work.',
        context: 'It\'s the second time this quarter. Your deliverable is now late too.',
        options: [
          { id: 'wb_4a', text: '"Hey, I noticed the report isn\'t in yet. What happened, and how can we get back on track?"', quality: 'best' },
          { id: 'wb_4b', text: '"You always miss deadlines and it makes me look bad."', quality: 'worst' },
          { id: 'wb_4c', text: 'Email your manager explaining the situation and CC your teammate.', quality: 'poor' },
          { id: 'wb_4d', text: '"No worries, I\'ll figure it out on my end."', quality: 'poor' },
        ],
        correctOptionId: 'wb_4a',
        explanation: 'Start with observation, not accusation. Ask what happened (curiosity, not blame) and pivot to solutions. This opens dialogue without triggering defensiveness.',
        skillTrack: 'connect',
      },
      {
        id: 'wb_5',
        scenario: 'You disagree with a decision your manager just made.',
        context: 'The decision affects your team\'s workflow. You have relevant data.',
        options: [
          { id: 'wb_5a', text: '"I\'d like to share some data I have that might affect this decision. Can we look at it together?"', quality: 'best' },
          { id: 'wb_5b', text: '"That\'s a bad call and here\'s why..."', quality: 'poor' },
          { id: 'wb_5c', text: 'Comply outwardly but tell your team you disagree.', quality: 'worst' },
          { id: 'wb_5d', text: '"I see where you\'re coming from, but have you considered...?"', quality: 'okay' },
        ],
        correctOptionId: 'wb_5a',
        explanation: 'Lead with new information rather than opposition. "I have data" is more persuasive than "I disagree." Make it collaborative by reviewing together.',
        skillTrack: 'negotiate',
      },
      {
        id: 'wb_6',
        scenario: 'A client yells at you over the phone about a minor issue.',
        context: 'The issue is easily fixable. The client is a long-term account.',
        options: [
          { id: 'wb_6a', text: '"I can hear this is really frustrating. Let me fix this right now — here\'s what I\'m going to do."', quality: 'best' },
          { id: 'wb_6b', text: '"You need to calm down. This isn\'t that big of a deal."', quality: 'worst' },
          { id: 'wb_6c', text: '"I\'m sorry, I\'m so sorry. I\'ll do whatever you need."', quality: 'poor' },
          { id: 'wb_6d', text: '"I understand. Let me look into this and get back to you."', quality: 'okay' },
        ],
        correctOptionId: 'wb_6a',
        explanation: 'Label the emotion ("frustrating"), then immediately pivot to action. Don\'t over-apologize or tell them to calm down. Show competence through swift action.',
        skillTrack: 'empathize',
      },
      {
        id: 'wb_7',
        scenario: 'Someone gossips to you about a colleague\'s personal life.',
        context: 'The person gossiping is friendly with you and expects engagement.',
        options: [
          { id: 'wb_7a', text: '"I\'d rather not get into that — how\'s your project going?"', quality: 'best' },
          { id: 'wb_7b', text: 'Listen politely but don\'t repeat the information.', quality: 'okay' },
          { id: 'wb_7c', text: '"Wow, really? Tell me more..."', quality: 'worst' },
          { id: 'wb_7d', text: '"That\'s none of our business and we shouldn\'t talk about it."', quality: 'poor' },
        ],
        correctOptionId: 'wb_7a',
        explanation: 'Clean redirect without preaching. State your preference, then offer an easy alternative topic. Doesn\'t damage the relationship or make them feel judged.',
        skillTrack: 'defend',
      },
      {
        id: 'wb_8',
        scenario: 'You receive harsh, public criticism on your presentation.',
        context: 'A senior leader criticizes your approach in front of 20 people.',
        options: [
          { id: 'wb_8a', text: '"Thank you for that feedback. Can you help me understand what specifically you\'d change?"', quality: 'best' },
          { id: 'wb_8b', text: '"Well, if you had read the brief, you\'d know why I took this approach."', quality: 'worst' },
          { id: 'wb_8c', text: 'Nod silently and move on to the next slide.', quality: 'poor' },
          { id: 'wb_8d', text: '"That\'s a fair point. Let me think about how to incorporate that."', quality: 'okay' },
        ],
        correctOptionId: 'wb_8a',
        explanation: 'Accept gracefully, then redirect with a calibrated question. Asking "what specifically" puts the burden on them to be constructive, not just critical.',
        skillTrack: 'regulate',
      },
      {
        id: 'wb_9',
        scenario: 'A new hire asks you to do something that\'s clearly their responsibility.',
        context: 'They seem overwhelmed and it would only take you 10 minutes.',
        options: [
          { id: 'wb_9a', text: '"I can walk you through how to do it — that way you\'ll have it for next time."', quality: 'best' },
          { id: 'wb_9b', text: '"That\'s your job, not mine."', quality: 'poor' },
          { id: 'wb_9c', text: 'Just do it for them to be nice.', quality: 'poor' },
          { id: 'wb_9d', text: '"Sure, I\'ll handle it this time."', quality: 'okay' },
        ],
        correctOptionId: 'wb_9a',
        explanation: 'Help without enabling. Teaching them builds capability and sets a healthy precedent — you\'re supportive but not a crutch.',
        skillTrack: 'connect',
      },
      {
        id: 'wb_10',
        scenario: 'You overhear your manager speaking negatively about you to another manager.',
        context: 'They said you "lack initiative" which contradicts your recent performance.',
        options: [
          { id: 'wb_10a', text: 'Schedule a 1-on-1 and say: "I\'d like to understand your expectations for initiative — I want to make sure we\'re aligned."', quality: 'best' },
          { id: 'wb_10b', text: 'Confront them immediately: "I heard what you said about me."', quality: 'poor' },
          { id: 'wb_10c', text: 'Start looking for a new job without addressing it.', quality: 'worst' },
          { id: 'wb_10d', text: 'Document it and bring it up at your next review.', quality: 'okay' },
        ],
        correctOptionId: 'wb_10a',
        explanation: 'Address the substance without revealing the eavesdrop. Frame it as seeking clarity, not confrontation. This opens a productive conversation.',
        skillTrack: 'negotiate',
      },
    ],
  },
  {
    id: 'relationship_rapids',
    title: 'Relationship Rapids',
    description: 'Handle tricky moments in romantic and close relationships',
    difficulty: 2,
    questions: [
      {
        id: 'rr_1',
        scenario: 'Your partner says "Fine, do whatever you want" in a cold tone.',
        context: 'You asked about plans for the weekend. They seem upset.',
        options: [
          { id: 'rr_1a', text: '"It sounds like something is bothering you. I\'d rather talk about it than guess."', quality: 'best' },
          { id: 'rr_1b', text: '"Okay, great!" and proceed with your plans.', quality: 'worst' },
          { id: 'rr_1c', text: '"Why are you being like this?"', quality: 'poor' },
          { id: 'rr_1d', text: '"I can tell you\'re upset. Take your time and let me know when you want to talk."', quality: 'okay' },
        ],
        correctOptionId: 'rr_1a',
        explanation: 'Name what you observe without accusing. "Something is bothering you" validates their emotion. Saying "I\'d rather talk" shows investment without forcing the conversation.',
        skillTrack: 'listen',
      },
      {
        id: 'rr_2',
        scenario: 'Your partner criticizes how you loaded the dishwasher.',
        context: 'You just finished cleaning the entire kitchen. This feels petty.',
        options: [
          { id: 'rr_2a', text: '"I hear you — is the dishwasher what\'s really bugging you, or is something else going on?"', quality: 'best' },
          { id: 'rr_2b', text: '"I just cleaned the ENTIRE kitchen and you\'re focusing on the dishwasher?!"', quality: 'poor' },
          { id: 'rr_2c', text: '"Fine, you do it then."', quality: 'worst' },
          { id: 'rr_2d', text: '"Sorry, I\'ll redo it."', quality: 'poor' },
        ],
        correctOptionId: 'rr_2a',
        explanation: 'Small complaints are often proxies for bigger feelings. Gently checking beneath the surface shows emotional intelligence and often reveals the real issue.',
        skillTrack: 'empathize',
      },
      {
        id: 'rr_3',
        scenario: 'Your partner wants to spend the holidays with their family, but you already told yours you\'d visit.',
        context: 'Both families live far away. This comes up every year.',
        options: [
          { id: 'rr_3a', text: '"This keeps coming up. Can we sit down and create a plan that works for both families long-term?"', quality: 'best' },
          { id: 'rr_3b', text: '"I already committed, so we\'re going to mine this year."', quality: 'poor' },
          { id: 'rr_3c', text: '"Fine, we\'ll go to yours. Whatever."', quality: 'worst' },
          { id: 'rr_3d', text: '"What if we split the time — a few days with each family?"', quality: 'okay' },
        ],
        correctOptionId: 'rr_3a',
        explanation: 'Zoom out from this year\'s conflict to create a systemic solution. Naming the pattern ("keeps coming up") and proposing a framework prevents annual arguments.',
        skillTrack: 'negotiate',
      },
      {
        id: 'rr_4',
        scenario: 'During an argument, your partner says "You\'re just like your mother."',
        context: 'You were discussing finances. This feels like a low blow.',
        options: [
          { id: 'rr_4a', text: '"That hurt. I need us to stay on the topic of finances without personal attacks."', quality: 'best' },
          { id: 'rr_4b', text: '"At least my mother isn\'t [insult]."', quality: 'worst' },
          { id: 'rr_4c', text: 'Walk away without saying anything.', quality: 'poor' },
          { id: 'rr_4d', text: '"That\'s not fair and you know it."', quality: 'okay' },
        ],
        correctOptionId: 'rr_4a',
        explanation: 'Name the impact ("that hurt"), set the boundary (no personal attacks), and redirect to the actual topic. Three moves in one sentence.',
        skillTrack: 'defend',
      },
      {
        id: 'rr_5',
        scenario: 'Your partner has been glued to their phone all evening and you feel ignored.',
        context: 'You\'ve been sitting together for 2 hours but haven\'t really talked.',
        options: [
          { id: 'rr_5a', text: '"I miss connecting with you. Can we put phones away for a bit and just hang out?"', quality: 'best' },
          { id: 'rr_5b', text: '"You\'re always on your phone. You never pay attention to me."', quality: 'worst' },
          { id: 'rr_5c', text: 'Start scrolling your own phone to make a passive-aggressive point.', quality: 'poor' },
          { id: 'rr_5d', text: '"Hey, whatcha looking at?"', quality: 'okay' },
        ],
        correctOptionId: 'rr_5a',
        explanation: 'Lead with what you want (connection), not what they\'re doing wrong (phone). "I miss connecting" is vulnerable and inviting. "You\'re always on your phone" triggers defense.',
        skillTrack: 'connect',
      },
      {
        id: 'rr_6',
        scenario: 'Your partner apologizes but it feels hollow: "Sorry if that bothered you."',
        context: 'They said something hurtful yesterday and you brought it up.',
        options: [
          { id: 'rr_6a', text: '"I appreciate you saying that. What I really need to hear is that you understand why it hurt."', quality: 'best' },
          { id: 'rr_6b', text: '"That\'s not a real apology."', quality: 'poor' },
          { id: 'rr_6c', text: '"Whatever, forget it."', quality: 'worst' },
          { id: 'rr_6d', text: '"It\'s okay, don\'t worry about it."', quality: 'poor' },
        ],
        correctOptionId: 'rr_6a',
        explanation: 'Acknowledge their attempt, then clearly state what a meaningful apology looks like for you. This teaches them how to repair with you without dismissing their effort.',
        skillTrack: 'assert',
      },
      {
        id: 'rr_7',
        scenario: 'Your partner makes a big financial decision without consulting you.',
        context: 'They bought an expensive item you didn\'t discuss. Shared finances.',
        options: [
          { id: 'rr_7a', text: '"I was surprised to see that purchase. Can we talk about how we make financial decisions together?"', quality: 'best' },
          { id: 'rr_7b', text: '"How could you spend that without asking me?!"', quality: 'poor' },
          { id: 'rr_7c', text: 'Go buy something equally expensive to "even the score."', quality: 'worst' },
          { id: 'rr_7d', text: '"I\'m not comfortable with that. Can you return it?"', quality: 'okay' },
        ],
        correctOptionId: 'rr_7a',
        explanation: 'State the observation calmly, then shift to the process issue. The problem isn\'t this one purchase — it\'s the lack of shared decision-making. Address the system.',
        skillTrack: 'negotiate',
      },
      {
        id: 'rr_8',
        scenario: 'Your partner says "We need to talk about our relationship."',
        context: 'You\'re blindsided. Things seemed fine to you.',
        options: [
          { id: 'rr_8a', text: '"I\'m glad you brought it up. I\'m here and I want to hear what\'s on your mind."', quality: 'best' },
          { id: 'rr_8b', text: '"Are you breaking up with me?!"', quality: 'poor' },
          { id: 'rr_8c', text: '"Everything is fine, what are you talking about?"', quality: 'worst' },
          { id: 'rr_8d', text: '"Okay... what about it?"', quality: 'okay' },
        ],
        correctOptionId: 'rr_8a',
        explanation: 'Validate their courage in raising a difficult topic. Show openness and presence. This creates safety for an honest conversation.',
        skillTrack: 'listen',
      },
      {
        id: 'rr_9',
        scenario: 'Your partner cries during an argument and you feel manipulated.',
        context: 'This happens frequently when you try to discuss problems.',
        options: [
          { id: 'rr_9a', text: '"I can see you\'re upset. Let\'s pause, and I\'d like us to come back to this when we\'re both ready."', quality: 'best' },
          { id: 'rr_9b', text: '"You always cry to avoid the conversation."', quality: 'worst' },
          { id: 'rr_9c', text: 'Drop the issue completely and comfort them.', quality: 'poor' },
          { id: 'rr_9d', text: '"I didn\'t mean to make you cry. Let\'s just forget it."', quality: 'poor' },
        ],
        correctOptionId: 'rr_9a',
        explanation: 'Acknowledge their emotion while preserving the conversation. "Let\'s pause" respects their feelings; "come back to this" ensures the topic isn\'t avoided.',
        skillTrack: 'regulate',
      },
      {
        id: 'rr_10',
        scenario: 'Your partner gives you the silent treatment after a disagreement.',
        context: 'It\'s been 6 hours. Your attempts to talk have been met with one-word answers.',
        options: [
          { id: 'rr_10a', text: '"I want to resolve this. I\'ll give you space, but I\'d like us to talk before bed. Would that work?"', quality: 'best' },
          { id: 'rr_10b', text: '"Fine, two can play that game." Give them the silent treatment back.', quality: 'worst' },
          { id: 'rr_10c', text: 'Keep pressing them to talk until they respond.', quality: 'poor' },
          { id: 'rr_10d', text: '"I\'m sorry if I did something wrong. Please talk to me."', quality: 'poor' },
        ],
        correctOptionId: 'rr_10a',
        explanation: 'State your intent (resolve), offer space (respect), and propose a timeline (structure). You\'re not chasing or withdrawing — you\'re creating a bridge.',
        skillTrack: 'connect',
      },
    ],
  },
  {
    id: 'social_pressure',
    title: 'Social Pressure Cooker',
    description: 'Handle peer pressure, pushy people, and awkward social situations',
    difficulty: 3,
    questions: [
      {
        id: 'sp_1',
        scenario: 'Friends pressure you to drink when you\'ve decided not to tonight.',
        context: 'Group dinner, everyone else is drinking. "Come on, just one!"',
        options: [
          { id: 'sp_1a', text: '"I\'m good tonight, but I\'m happy to be the one who remembers everything tomorrow."', quality: 'best' },
          { id: 'sp_1b', text: '"Fine, just one" even though you don\'t want to.', quality: 'worst' },
          { id: 'sp_1c', text: '"I said no. Why can\'t you respect that?"', quality: 'poor' },
          { id: 'sp_1d', text: '"Not tonight, thanks." (Repeat as needed)', quality: 'okay' },
        ],
        correctOptionId: 'sp_1a',
        explanation: 'Confident refusal + humor deflects pressure without creating tension. You hold your boundary while keeping the energy light.',
        skillTrack: 'defend',
      },
      {
        id: 'sp_2',
        scenario: 'Someone you barely know asks to borrow a significant amount of money.',
        context: 'Acquaintance at a social event, asks for $500 "just for a week."',
        options: [
          { id: 'sp_2a', text: '"I have a personal rule about not lending money — it\'s nothing personal. Hope you figure it out."', quality: 'best' },
          { id: 'sp_2b', text: '"Sure, I guess..." even though you\'re uncomfortable.', quality: 'worst' },
          { id: 'sp_2c', text: '"No way, I barely know you."', quality: 'poor' },
          { id: 'sp_2d', text: '"I can\'t right now, sorry."', quality: 'okay' },
        ],
        correctOptionId: 'sp_2a',
        explanation: 'A "personal rule" depersonalizes the refusal — it\'s not about them, it\'s about your policy. Adding "hope you figure it out" shows warmth without caving.',
        skillTrack: 'defend',
      },
      {
        id: 'sp_3',
        scenario: 'Someone makes a racist joke and everyone laughs. You\'re uncomfortable.',
        context: 'Party with mixed company. The joke was clearly offensive.',
        options: [
          { id: 'sp_3a', text: '"I don\'t think that\'s funny. Can we move on?"', quality: 'best' },
          { id: 'sp_3b', text: 'Laugh along to avoid being "that person."', quality: 'worst' },
          { id: 'sp_3c', text: 'Launch into a lecture about why it\'s offensive.', quality: 'poor' },
          { id: 'sp_3d', text: 'Don\'t laugh but say nothing.', quality: 'okay' },
        ],
        correctOptionId: 'sp_3a',
        explanation: 'Brief, clear, and redirecting. You state your position without grandstanding. "Can we move on?" gives the group an exit without a prolonged confrontation.',
        skillTrack: 'assert',
      },
      {
        id: 'sp_4',
        scenario: 'A persistent salesperson won\'t take no for an answer.',
        context: 'You said no twice. They\'re using every tactic in the book.',
        options: [
          { id: 'sp_4a', text: '"I appreciate your persistence, but my answer is no. I\'m going to end this conversation now."', quality: 'best' },
          { id: 'sp_4b', text: '"Maybe, let me think about it..." to escape the conversation.', quality: 'poor' },
          { id: 'sp_4c', text: '"STOP. Leave me alone!"', quality: 'poor' },
          { id: 'sp_4d', text: 'Give in because the pressure is too much.', quality: 'worst' },
        ],
        correctOptionId: 'sp_4a',
        explanation: 'Acknowledge their effort, state a clear final answer, and announce the end. You control the exit. "Maybe" just extends the pressure.',
        skillTrack: 'defend',
      },
      {
        id: 'sp_5',
        scenario: 'A friend constantly one-ups every story you tell.',
        context: 'You shared a vacation story, and they immediately told a "better" one.',
        options: [
          { id: 'sp_5a', text: '"That sounds great! I\'d actually love to finish my story first — then I want to hear all about yours."', quality: 'best' },
          { id: 'sp_5b', text: 'Stop sharing stories with them entirely.', quality: 'poor' },
          { id: 'sp_5c', text: '"Why do you always have to one-up me?"', quality: 'poor' },
          { id: 'sp_5d', text: 'Just let it go, it\'s not worth the conflict.', quality: 'okay' },
        ],
        correctOptionId: 'sp_5a',
        explanation: 'Warm but firm. You validate their story, assert your right to finish yours, and promise to listen. This models good conversation without shaming.',
        skillTrack: 'assert',
      },
      {
        id: 'sp_6',
        scenario: 'Someone asks an invasive personal question at a family gathering.',
        context: '"So when are you two having kids?" In front of everyone.',
        options: [
          { id: 'sp_6a', text: '"That\'s between us for now! So what have YOU been up to lately?"', quality: 'best' },
          { id: 'sp_6b', text: 'Answer honestly even though you\'re uncomfortable.', quality: 'poor' },
          { id: 'sp_6c', text: '"That\'s incredibly rude to ask."', quality: 'poor' },
          { id: 'sp_6d', text: '"Haha, we\'ll see!" with a forced smile.', quality: 'okay' },
        ],
        correctOptionId: 'sp_6a',
        explanation: 'Cheerful boundary + immediate redirect. The exclamation keeps the tone light while the redirect takes pressure off you. No explanation needed.',
        skillTrack: 'defend',
      },
      {
        id: 'sp_7',
        scenario: 'Two friends are fighting and both want you to pick a side.',
        context: 'Each has called you separately to vent. You care about both.',
        options: [
          { id: 'sp_7a', text: '"I care about both of you. I\'m happy to listen, but I\'m not going to pick sides — I think you two should talk directly."', quality: 'best' },
          { id: 'sp_7b', text: 'Agree with whoever you\'re talking to at the moment.', quality: 'worst' },
          { id: 'sp_7c', text: '"I don\'t want to be involved in this."', quality: 'okay' },
          { id: 'sp_7d', text: 'Try to mediate and fix it for them.', quality: 'poor' },
        ],
        correctOptionId: 'sp_7a',
        explanation: 'State your care, set your boundary (won\'t pick sides), and redirect them to the source. You remain supportive without becoming a pawn in their conflict.',
        skillTrack: 'regulate',
      },
      {
        id: 'sp_8',
        scenario: 'Someone at a party keeps touching your arm and standing too close.',
        context: 'You\'ve stepped back twice. They keep closing the gap.',
        options: [
          { id: 'sp_8a', text: '"I need a little more space — thanks for understanding." Take a step back firmly.', quality: 'best' },
          { id: 'sp_8b', text: 'Tolerate it to avoid making a scene.', quality: 'poor' },
          { id: 'sp_8c', text: '"Stop touching me!" loudly.', quality: 'okay' },
          { id: 'sp_8d', text: 'Leave the party without saying anything.', quality: 'poor' },
        ],
        correctOptionId: 'sp_8a',
        explanation: 'Direct verbal boundary with a physical action. "Thanks for understanding" is assertive — it assumes compliance rather than asking for permission.',
        skillTrack: 'defend',
      },
      {
        id: 'sp_9',
        scenario: 'A friend invites themselves on your solo vacation.',
        context: '"That sounds amazing! I\'m totally coming with you!"',
        options: [
          { id: 'sp_9a', text: '"I appreciate the enthusiasm! This one\'s actually a solo trip for me — let\'s plan something together another time though."', quality: 'best' },
          { id: 'sp_9b', text: '"Um, sure... I guess that could work."', quality: 'worst' },
          { id: 'sp_9c', text: '"No, this is MY trip."', quality: 'poor' },
          { id: 'sp_9d', text: '"I\'ll think about it" and then avoid them.', quality: 'poor' },
        ],
        correctOptionId: 'sp_9a',
        explanation: 'Validate their excitement, state your boundary clearly, and offer an alternative. You protect your space without rejecting the person.',
        skillTrack: 'assert',
      },
      {
        id: 'sp_10',
        scenario: 'A friend guilt-trips you for not attending their event.',
        context: '"I guess you just don\'t care about me as much as I care about you."',
        options: [
          { id: 'sp_10a', text: '"I care about you a lot. I can\'t make this one, but that doesn\'t change how I feel about our friendship."', quality: 'best' },
          { id: 'sp_10b', text: '"You\'re being manipulative right now."', quality: 'poor' },
          { id: 'sp_10c', text: 'Go to the event even though you can\'t/don\'t want to.', quality: 'worst' },
          { id: 'sp_10d', text: '"I\'m sorry, I really am. I\'ll make it up to you."', quality: 'okay' },
        ],
        correctOptionId: 'sp_10a',
        explanation: 'Affirm the relationship, hold your position, and separate the event from the friendship. You refuse the guilt frame without attacking them for using it.',
        skillTrack: 'regulate',
      },
    ],
  },
  {
    id: 'family_dynamics',
    title: 'Family Dynamics',
    description: 'Navigate guilt trips, boundary crossings, and complex family situations',
    difficulty: 3,
    questions: [
      {
        id: 'fd_1',
        scenario: 'Your parent says "After everything I\'ve sacrificed for you, you can\'t even visit for one weekend?"',
        context: 'You declined a visit because you had prior commitments.',
        options: [
          { id: 'fd_1a', text: '"I love you and I\'m grateful for everything. My schedule is full this weekend, but let\'s find a date that works for both of us."', quality: 'best' },
          { id: 'fd_1b', text: '"Stop guilt-tripping me. I have my own life."', quality: 'poor' },
          { id: 'fd_1c', text: '"You\'re right, I\'ll cancel my plans." Cancel reluctantly.', quality: 'worst' },
          { id: 'fd_1d', text: '"I\'m sorry, I feel terrible about it."', quality: 'poor' },
        ],
        correctOptionId: 'fd_1a',
        explanation: 'Affirm the relationship and gratitude without accepting the guilt frame. Then redirect to a solution. You can honor their feelings without surrendering your autonomy.',
        skillTrack: 'defend',
      },
      {
        id: 'fd_2',
        scenario: 'Your sibling criticizes your parenting in front of your children.',
        context: '"You really let them eat that? No wonder they\'re so hyper." Your kids are listening.',
        options: [
          { id: 'fd_2a', text: '"I appreciate your concern. Let\'s talk about parenting approaches later — not in front of the kids."', quality: 'best' },
          { id: 'fd_2b', text: '"At least my kids are happy. Yours seem miserable."', quality: 'worst' },
          { id: 'fd_2c', text: 'Ignore it and change the subject.', quality: 'okay' },
          { id: 'fd_2d', text: '"Mind your own business."', quality: 'poor' },
        ],
        correctOptionId: 'fd_2a',
        explanation: 'Acknowledge without agreeing, then set a boundary about timing and audience. Protects your children from witnessing adult conflict while preserving the relationship.',
        skillTrack: 'defend',
      },
      {
        id: 'fd_3',
        scenario: 'Your parent compares you unfavorably to a sibling at a family dinner.',
        context: '"Why can\'t you be more like your brother? He calls every day."',
        options: [
          { id: 'fd_3a', text: '"We each show love differently. I\'d like us to appreciate what I do bring rather than compare."', quality: 'best' },
          { id: 'fd_3b', text: '"Maybe he calls because he needs something."', quality: 'worst' },
          { id: 'fd_3c', text: 'Say nothing and seethe quietly.', quality: 'poor' },
          { id: 'fd_3d', text: '"I\'ll try to call more, sorry."', quality: 'poor' },
        ],
        correctOptionId: 'fd_3a',
        explanation: 'Name the pattern (comparison) and offer a reframe (different love languages). You don\'t need to compete with a sibling — redirect toward appreciation.',
        skillTrack: 'assert',
      },
      {
        id: 'fd_4',
        scenario: 'Your in-law makes passive-aggressive comments about your cooking.',
        context: '"Oh, this is... interesting. I usually make it differently, but I\'m sure this is fine."',
        options: [
          { id: 'fd_4a', text: '"I\'d love to learn your recipe! Maybe we can cook together next time."', quality: 'best' },
          { id: 'fd_4b', text: '"If you don\'t like it, don\'t eat it."', quality: 'poor' },
          { id: 'fd_4c', text: 'Feel hurt and never cook for them again.', quality: 'worst' },
          { id: 'fd_4d', text: '"Thanks, I tried my best."', quality: 'okay' },
        ],
        correctOptionId: 'fd_4a',
        explanation: 'Transform criticism into collaboration. By inviting them to share their way, you disarm the passive aggression and build connection. The power move is genuine curiosity.',
        skillTrack: 'connect',
      },
      {
        id: 'fd_5',
        scenario: 'Your elderly parent refuses to discuss their health or future care plans.',
        context: '"I don\'t want to talk about that. When it\'s my time, it\'s my time."',
        options: [
          { id: 'fd_5a', text: '"I hear you. I\'m not trying to rush anything — I just want to make sure I can support you the way you want. Can we revisit this when you\'re ready?"', quality: 'best' },
          { id: 'fd_5b', text: '"You\'re being irresponsible. What if something happens?"', quality: 'poor' },
          { id: 'fd_5c', text: 'Make plans behind their back with other family members.', quality: 'worst' },
          { id: 'fd_5d', text: '"Okay, we don\'t have to talk about it now."', quality: 'okay' },
        ],
        correctOptionId: 'fd_5a',
        explanation: 'Respect their autonomy while planting the seed. Framing it as "support you the way YOU want" centers their control, which is usually the real fear behind avoidance.',
        skillTrack: 'empathize',
      },
      {
        id: 'fd_6',
        scenario: 'Your adult child moves back home and doesn\'t contribute to household chores.',
        context: 'It\'s been 3 weeks. Dishes pile up, common areas are messy.',
        options: [
          { id: 'fd_6a', text: '"I\'m happy to have you here. Let\'s sit down and figure out a fair way to share the household responsibilities."', quality: 'best' },
          { id: 'fd_6b', text: '"You\'re an adult living in MY house. Clean up after yourself!"', quality: 'poor' },
          { id: 'fd_6c', text: 'Clean up after them and grow increasingly resentful.', quality: 'worst' },
          { id: 'fd_6d', text: 'Leave passive-aggressive notes around the house.', quality: 'poor' },
        ],
        correctOptionId: 'fd_6a',
        explanation: 'Lead with warmth, then structure. Creating a system together respects their adulthood while setting clear expectations. Avoids the parent-child dynamic that breeds resentment on both sides.',
        skillTrack: 'negotiate',
      },
      {
        id: 'fd_7',
        scenario: 'Your family member shares your private information at a holiday gathering.',
        context: 'They just told everyone about your job loss: "Did you all hear? They got laid off!"',
        options: [
          { id: 'fd_7a', text: '"I wasn\'t ready to share that yet. I\'d appreciate if we could talk to me before sharing my news in the future."', quality: 'best' },
          { id: 'fd_7b', text: '"Thanks for announcing that to everyone without my permission."', quality: 'okay' },
          { id: 'fd_7c', text: 'Smile and pretend it doesn\'t bother you.', quality: 'poor' },
          { id: 'fd_7d', text: 'Share something embarrassing about them in retaliation.', quality: 'worst' },
        ],
        correctOptionId: 'fd_7a',
        explanation: 'Name the impact without attacking. "I wasn\'t ready to share" communicates the violation. "Talk to me first" sets the boundary for the future. Clean, respectful, firm.',
        skillTrack: 'assert',
      },
      {
        id: 'fd_8',
        scenario: 'Your parent says "You\'ll understand when you\'re older" to dismiss your opinion.',
        context: 'You\'re 30. They use this line whenever you disagree with them.',
        options: [
          { id: 'fd_8a', text: '"I respect your experience. And I\'d like my perspective to be considered too, even if we end up disagreeing."', quality: 'best' },
          { id: 'fd_8b', text: '"I\'m an adult. Stop treating me like a child."', quality: 'poor' },
          { id: 'fd_8c', text: 'Drop it — they\'ll never see you as a peer.', quality: 'worst' },
          { id: 'fd_8d', text: '"Maybe, but I\'d still like to share my thoughts."', quality: 'okay' },
        ],
        correctOptionId: 'fd_8a',
        explanation: 'Honor their experience while asserting your right to contribute. You\'re not demanding they agree — you\'re asking to be heard. This shifts the dynamic from hierarchy to mutual respect.',
        skillTrack: 'assert',
      },
      {
        id: 'fd_9',
        scenario: 'Two family members start arguing loudly at dinner and everyone freezes.',
        context: 'Uncle and cousin are going at it about politics. Kids look uncomfortable.',
        options: [
          { id: 'fd_9a', text: '"Hey, let\'s take a break from this topic. Who wants dessert? We can always circle back later."', quality: 'best' },
          { id: 'fd_9b', text: 'Pick a side and join the argument.', quality: 'worst' },
          { id: 'fd_9c', text: '"Can you two please stop? You\'re ruining dinner."', quality: 'poor' },
          { id: 'fd_9d', text: 'Quietly leave the table.', quality: 'okay' },
        ],
        correctOptionId: 'fd_9a',
        explanation: 'Redirect without scolding. Offering an alternative activity gives everyone an off-ramp. "Circle back later" acknowledges the topic matters without letting it hijack the gathering.',
        skillTrack: 'regulate',
      },
      {
        id: 'fd_10',
        scenario: 'Your parent shows up unannounced when you\'ve asked them to call first.',
        context: 'Third time this month. You\'re in the middle of something important.',
        options: [
          { id: 'fd_10a', text: '"I love seeing you, and I need you to call first like we discussed. Can you give me 30 minutes and we\'ll have coffee?"', quality: 'best' },
          { id: 'fd_10b', text: '"Why do you keep doing this? I told you to call first!"', quality: 'poor' },
          { id: 'fd_10c', text: 'Let them in and abandon your plans.', quality: 'worst' },
          { id: 'fd_10d', text: '"Now\'s not a great time. Sorry."', quality: 'okay' },
        ],
        correctOptionId: 'fd_10a',
        explanation: 'Affirm the relationship, restate the boundary, and offer a structured compromise. You hold the line while showing it\'s about logistics, not rejection.',
        skillTrack: 'defend',
      },
    ],
  },
  {
    id: 'negotiation_moves',
    title: 'Negotiation Moves',
    description: 'Apply tactical empathy and calibrated questions in everyday negotiations',
    difficulty: 4,
    questions: [
      {
        id: 'nm_1',
        scenario: 'A car salesperson says "This is the absolute lowest I can go."',
        context: 'You\'ve been negotiating for 20 minutes. They seem firm.',
        options: [
          { id: 'nm_1a', text: '"How am I supposed to make that work with my budget?" (Pause and wait)', quality: 'best' },
          { id: 'nm_1b', text: '"I\'ll take it, I guess."', quality: 'worst' },
          { id: 'nm_1c', text: '"I know you can go lower. Stop playing games."', quality: 'poor' },
          { id: 'nm_1d', text: '"What if I pay cash?"', quality: 'okay' },
        ],
        correctOptionId: 'nm_1a',
        explanation: 'A calibrated "How" question puts the problem back on them without confrontation. Silence after is key — it creates pressure to fill the gap, often with a concession.',
        skillTrack: 'negotiate',
      },
      {
        id: 'nm_2',
        scenario: 'Your landlord wants to raise rent by 15% and says "Market rates have gone up."',
        context: 'You\'ve been a reliable tenant for 3 years. No late payments.',
        options: [
          { id: 'nm_2a', text: '"I understand rates have shifted. Given my track record here — 3 years, zero issues — what can we do to find a number that keeps me here?"', quality: 'best' },
          { id: 'nm_2b', text: '"That\'s outrageous. I\'m not paying that."', quality: 'poor' },
          { id: 'nm_2c', text: '"Fine." Sign the new lease.', quality: 'worst' },
          { id: 'nm_2d', text: '"Can we meet in the middle — say 8%?"', quality: 'okay' },
        ],
        correctOptionId: 'nm_2a',
        explanation: 'Acknowledge their position, present your value (reliable tenant = real savings for them), then use a calibrated question. You\'re negotiating from strength without threatening.',
        skillTrack: 'negotiate',
      },
      {
        id: 'nm_3',
        scenario: 'You\'re asked to take on extra work with no additional pay.',
        context: '"We\'re short-staffed and really need you to step up." No timeline given.',
        options: [
          { id: 'nm_3a', text: '"I want to help. What would change in my current workload or compensation to make that sustainable?"', quality: 'best' },
          { id: 'nm_3b', text: '"That\'s not my job. Pay me more or hire someone."', quality: 'poor' },
          { id: 'nm_3c', text: '"Sure, I\'ll handle it." (Work 60-hour weeks)', quality: 'worst' },
          { id: 'nm_3d', text: '"I can help short-term. Can we revisit this in two weeks?"', quality: 'okay' },
        ],
        correctOptionId: 'nm_3a',
        explanation: 'Express willingness, then use a "What" question to make them think about the trade-offs. Forces them to address workload or compensation — you\'re not saying no, you\'re asking how.',
        skillTrack: 'negotiate',
      },
      {
        id: 'nm_4',
        scenario: 'A contractor quotes double what you expected for a home repair.',
        context: 'You got one other quote that was significantly lower.',
        options: [
          { id: 'nm_4a', text: '"Help me understand what goes into this price. I want to make sure I\'m comparing apples to apples."', quality: 'best' },
          { id: 'nm_4b', text: '"Another guy quoted me half that. Can you match it?"', quality: 'okay' },
          { id: 'nm_4c', text: '"That\'s way too much. Forget it."', quality: 'poor' },
          { id: 'nm_4d', text: 'Accept the quote because you don\'t want conflict.', quality: 'worst' },
        ],
        correctOptionId: 'nm_4a',
        explanation: 'Seek understanding before pushing back. Their quote might include things the cheaper one doesn\'t. "Help me understand" is non-confrontational and might reveal the real value — or room to negotiate.',
        skillTrack: 'negotiate',
      },
      {
        id: 'nm_5',
        scenario: 'Your friend borrowed something months ago and keeps "forgetting" to return it.',
        context: 'You\'ve mentioned it twice. They changed the subject both times.',
        options: [
          { id: 'nm_5a', text: '"Hey, I need my [item] back by Friday. What works for picking it up or me swinging by?"', quality: 'best' },
          { id: 'nm_5b', text: '"You still have my stuff. It\'s been months."', quality: 'okay' },
          { id: 'nm_5c', text: 'Write it off to avoid awkwardness.', quality: 'poor' },
          { id: 'nm_5d', text: 'Complain about it to mutual friends.', quality: 'worst' },
        ],
        correctOptionId: 'nm_5a',
        explanation: 'Specific deadline + two concrete options eliminates ambiguity. They can\'t "forget" when you\'ve offered to pick it up. Direct without dramatic.',
        skillTrack: 'assert',
      },
      {
        id: 'nm_6',
        scenario: 'In a salary negotiation, the hiring manager says "That\'s the best we can offer."',
        context: 'The offer is 10% below your target. You really want this job.',
        options: [
          { id: 'nm_6a', text: '"I\'m excited about this role. If the base salary is fixed, what flexibility is there on signing bonus, vacation days, or remote work?"', quality: 'best' },
          { id: 'nm_6b', text: '"Then I\'ll have to decline."', quality: 'poor' },
          { id: 'nm_6c', text: '"Okay, I\'ll take it." (Feel undervalued from day one)', quality: 'worst' },
          { id: 'nm_6d', text: '"Can you do just $5K more?"', quality: 'okay' },
        ],
        correctOptionId: 'nm_6a',
        explanation: 'When one door closes, open others. Non-salary compensation is often more flexible. Framing it as "what flexibility is there" invites creative solutions rather than a yes/no on salary.',
        skillTrack: 'negotiate',
      },
      {
        id: 'nm_7',
        scenario: 'A service provider gives you a "take it or leave it" ultimatum.',
        context: '"That\'s the price. If you don\'t want it, someone else will."',
        options: [
          { id: 'nm_7a', text: '"I hear you. Before I decide — what would a longer commitment or referral from me be worth to you?"', quality: 'best' },
          { id: 'nm_7b', text: '"Fine, I\'ll find someone else." (Storm off)', quality: 'poor' },
          { id: 'nm_7c', text: '"Okay, fine." (Pay resentfully)', quality: 'worst' },
          { id: 'nm_7d', text: '"Can you throw in something extra then?"', quality: 'okay' },
        ],
        correctOptionId: 'nm_7a',
        explanation: 'Don\'t accept the frame of "take it or leave it." Introduce new variables — long-term commitment, referrals, volume. Change the equation rather than accepting their terms.',
        skillTrack: 'negotiate',
      },
      {
        id: 'nm_8',
        scenario: 'You want a refund for a product that\'s past the return window.',
        context: 'The product broke 2 days after the return period ended. Store policy says no.',
        options: [
          { id: 'nm_8a', text: '"I understand the policy. Given that it broke so close to the window, what\'s the most you\'re able to do for me — exchange, store credit, anything?"', quality: 'best' },
          { id: 'nm_8b', text: '"This is ridiculous. I want to speak to a manager."', quality: 'poor' },
          { id: 'nm_8c', text: '"Never mind." Leave and post a bad review.', quality: 'worst' },
          { id: 'nm_8d', text: '"Can you make an exception just this once?"', quality: 'okay' },
        ],
        correctOptionId: 'nm_8a',
        explanation: 'Acknowledge the policy (shows respect), highlight the circumstance, then ask "what\'s the most you can do" — this psychological phrasing makes the rep work to find the maximum they\'re authorized to offer.',
        skillTrack: 'negotiate',
      },
      {
        id: 'nm_9',
        scenario: 'A client wants you to reduce your rate significantly for a project.',
        context: '"We love your work but our budget is tight. Can you do it for half?"',
        options: [
          { id: 'nm_9a', text: '"I appreciate that. At half the rate, what scope reduction would work for your budget? I can tailor a package."', quality: 'best' },
          { id: 'nm_9b', text: '"My rates are my rates. Take it or leave it."', quality: 'poor' },
          { id: 'nm_9c', text: '"Sure, I want the work." (Resent it the whole time)', quality: 'worst' },
          { id: 'nm_9d', text: '"How about a 20% discount?"', quality: 'okay' },
        ],
        correctOptionId: 'nm_9a',
        explanation: 'Never discount without reducing scope. This protects your value while offering flexibility. "What scope reduction" makes them choose what to cut — they often realize they need the full package.',
        skillTrack: 'negotiate',
      },
      {
        id: 'nm_10',
        scenario: 'Your partner wants to make a big purchase you think is unnecessary.',
        context: 'They\'ve been excited about it for weeks. It\'s expensive but won\'t cause financial hardship.',
        options: [
          { id: 'nm_10a', text: '"I can see how much this means to you. Can we look at our budget together and figure out the best way to make it work?"', quality: 'best' },
          { id: 'nm_10b', text: '"That\'s a waste of money. No."', quality: 'worst' },
          { id: 'nm_10c', text: '"Whatever, it\'s your money." (Silently judge)', quality: 'poor' },
          { id: 'nm_10d', text: '"Can we wait a month and see if you still want it?"', quality: 'okay' },
        ],
        correctOptionId: 'nm_10a',
        explanation: 'Validate their excitement, then collaborate on the how. You\'re not gatekeeping — you\'re partnering. Looking at the budget together often naturally surfaces trade-offs without you being the "no" person.',
        skillTrack: 'connect',
      },
    ],
  },
];

export function getFlashSetById(id: string): FlashJudgmentSet | undefined {
  return FLASH_JUDGMENT_SETS.find((s) => s.id === id);
}
