export interface DecoderSet {
  id: string;
  title: string;
  description: string;
  difficulty: number;
  cards: DecoderCard[];
}

export interface DecoderCard {
  id: string;
  situation: string;
  statement: string;
  speaker: string;
  bodyLanguage: string;
  surfaceEmotion: string;
  hiddenEmotion: string;
  hiddenEmotionId: string;
  decoyEmotions: string[];
  explanation: string;
  betterResponse: string;
}

export const EMOTION_OPTIONS = [
  { id: 'fear', label: 'Fear', icon: 'alert-circle-outline', color: '#D29922' },
  { id: 'shame', label: 'Shame', icon: 'eye-off-outline', color: '#7B2D8E' },
  { id: 'loneliness', label: 'Loneliness', icon: 'account-off-outline', color: '#7B68EE' },
  { id: 'grief', label: 'Grief', icon: 'heart-broken-outline', color: '#45B7D1' },
  { id: 'inadequacy', label: 'Inadequacy', icon: 'thumb-down-outline', color: '#4A5568' },
  { id: 'rejection', label: 'Rejection', icon: 'account-remove-outline', color: '#D93025' },
  { id: 'helplessness', label: 'Helplessness', icon: 'hand-back-left-outline', color: '#8B949E' },
  { id: 'jealousy', label: 'Jealousy', icon: 'eye-outline', color: '#2EA043' },
  { id: 'betrayal', label: 'Betrayal', icon: 'shield-off-outline', color: '#F85149' },
  { id: 'overwhelm', label: 'Overwhelm', icon: 'waves', color: '#FF8C42' },
  { id: 'resentment', label: 'Resentment', icon: 'thought-bubble-outline', color: '#8B6914' },
  { id: 'vulnerability', label: 'Vulnerability', icon: 'shield-alert-outline', color: '#FF69B4' },
];

export const DECODER_SETS: DecoderSet[] = [
  {
    id: 'anger_beneath',
    title: 'What\'s Behind the Anger',
    description: 'Decode what people really feel when they express anger',
    difficulty: 2,
    cards: [
      {
        id: 'ab_1',
        situation: 'Your teenage daughter slams the door and yells "I hate this family!"',
        statement: '"I HATE this family! Nobody ever listens to me! I wish I could just leave!"',
        speaker: 'Your daughter (15)',
        bodyLanguage: 'Tears in eyes, clenched fists, voice cracking',
        surfaceEmotion: 'Anger / Rage',
        hiddenEmotion: 'Helplessness',
        hiddenEmotionId: 'helplessness',
        decoyEmotions: ['jealousy', 'shame', 'betrayal'],
        explanation: 'The explosive anger masks a deep sense of powerlessness. She doesn\'t feel heard or valued, and the only way she knows to express that is through intensity. The tears and cracking voice reveal the vulnerability underneath.',
        betterResponse: '"I can see you\'re really hurting right now. I want to hear what\'s going on. Can we talk when you\'re ready?"',
      },
      {
        id: 'ab_2',
        situation: 'Your partner snaps at you for not doing the dishes.',
        statement: '"Why can\'t you just DO things without me having to ASK? I\'m not your mother!"',
        speaker: 'Your partner',
        bodyLanguage: 'Arms crossed, won\'t make eye contact, jaw tight',
        surfaceEmotion: 'Frustration / Contempt',
        hiddenEmotion: 'Feeling invisible and undervalued',
        hiddenEmotionId: 'inadequacy',
        decoyEmotions: ['jealousy', 'grief', 'betrayal'],
        explanation: 'The dishes are a proxy. Underneath the anger is a feeling of being taken for granted — that their contributions go unnoticed while they\'re expected to manage everything. They feel more like a caretaker than an equal partner.',
        betterResponse: '"You\'re right that I should be more proactive. I think this is about more than dishes — are you feeling like things aren\'t balanced?"',
      },
      {
        id: 'ab_3',
        situation: 'Your friend aggressively criticizes your new hobby.',
        statement: '"Pottery? Really? That\'s the most pointless thing I\'ve ever heard. What a waste of time."',
        speaker: 'Your friend',
        bodyLanguage: 'Nervous laugh, scrolling phone, dismissive hand wave',
        surfaceEmotion: 'Mockery / Disdain',
        hiddenEmotion: 'Jealousy',
        hiddenEmotionId: 'jealousy',
        decoyEmotions: ['helplessness', 'shame', 'loneliness'],
        explanation: 'When someone aggressively mocks your growth, they often feel threatened by it. Your new interest highlights that they\'re not pursuing anything meaningful, triggering envy disguised as contempt.',
        betterResponse: '"Seems like that hit a nerve. I\'d love it if you tried it with me sometime."',
      },
      {
        id: 'ab_4',
        situation: 'Your coworker angrily confronts you about going to lunch without them.',
        statement: '"Thanks for the invite. Oh wait, I didn\'t get one. Good to know where I stand with this team."',
        speaker: 'Coworker',
        bodyLanguage: 'Fake smile, stiff posture, speaking louder than necessary',
        surfaceEmotion: 'Sarcasm / Passive aggression',
        hiddenEmotion: 'Fear of being excluded and rejected',
        hiddenEmotionId: 'rejection',
        decoyEmotions: ['resentment', 'shame', 'overwhelm'],
        explanation: 'The sarcasm is armor. Underneath is a genuine fear of not belonging. Saying "I feel left out" feels too vulnerable, so they weaponize it instead.',
        betterResponse: '"I\'m sorry we didn\'t ask — it wasn\'t intentional. You\'re always welcome. Want to grab coffee this afternoon?"',
      },
      {
        id: 'ab_5',
        situation: 'Your father blows up when you mention visiting less often.',
        statement: '"Fine! Don\'t bother coming at all then. I managed alone before you were born, I can manage again!"',
        speaker: 'Your father (68)',
        bodyLanguage: 'Turns away, voice rises then drops, hand on forehead',
        surfaceEmotion: 'Defiance / Pride',
        hiddenEmotion: 'Fear of abandonment and loneliness',
        hiddenEmotionId: 'loneliness',
        decoyEmotions: ['shame', 'inadequacy', 'resentment'],
        explanation: 'The "I don\'t need you" posture is a protective mechanism against the terror of being alone. Aging + reduced visits triggers abandonment fear. He pushes away before he can be left behind.',
        betterResponse: '"I\'m not going anywhere, Dad. I love you. Let\'s figure out a schedule that works for both of us."',
      },
      {
        id: 'ab_6',
        situation: 'Your sibling accuses you of being the "favorite child."',
        statement: '"Of course Mom calls you first. You\'ve always been the golden child. Must be nice."',
        speaker: 'Your sibling',
        bodyLanguage: 'Staring at the floor, picking at fingernails, bitter tone',
        surfaceEmotion: 'Resentment / Bitterness',
        hiddenEmotion: 'Feeling inadequate and unseen',
        hiddenEmotionId: 'inadequacy',
        decoyEmotions: ['betrayal', 'loneliness', 'fear'],
        explanation: 'The accusation of favoritism reflects a lifelong wound of feeling "not enough." They\'re not actually angry at you — they\'re grieving the parental validation they never felt they received.',
        betterResponse: '"I hear you. I know Mom and I are close, but that doesn\'t mean she doesn\'t love you. How are you feeling about your relationship with her?"',
      },
      {
        id: 'ab_7',
        situation: 'A client furiously demands a refund over a minor issue.',
        statement: '"This is COMPLETELY unacceptable! I\'ve been a customer for TEN YEARS and this is how you treat me?!"',
        speaker: 'Long-time client',
        bodyLanguage: 'Red face, leaning forward, finger pointing',
        surfaceEmotion: 'Outrage / Indignation',
        hiddenEmotion: 'Feeling disrespected and undervalued',
        hiddenEmotionId: 'rejection',
        decoyEmotions: ['overwhelm', 'grief', 'jealousy'],
        explanation: 'The disproportionate reaction reveals that this isn\'t about the minor issue — it\'s about feeling like their loyalty doesn\'t matter. They need to feel seen and valued, not just serviced.',
        betterResponse: '"Ten years means a lot to us, and you deserve better than this. Let me make it right personally."',
      },
      {
        id: 'ab_8',
        situation: 'Your partner explodes after you get a job offer in another city.',
        statement: '"So you just decided for both of us?! What about what I want? Do I even matter?"',
        speaker: 'Partner',
        bodyLanguage: 'Pacing, hands through hair, voice shaking',
        surfaceEmotion: 'Anger / Betrayal',
        hiddenEmotion: 'Fear of losing the relationship',
        hiddenEmotionId: 'fear',
        decoyEmotions: ['resentment', 'shame', 'helplessness'],
        explanation: 'The anger is a response to a perceived threat to the relationship. "Do I even matter?" reveals the core fear — that you\'d choose career over them. They need reassurance of their importance.',
        betterResponse: '"You absolutely matter. I haven\'t decided anything — I want to figure this out together. What are your fears?"',
      },
    ],
  },
  {
    id: 'silence_speaks',
    title: 'When Silence Speaks',
    description: 'Decode withdrawal, avoidance, and emotional shutdowns',
    difficulty: 3,
    cards: [
      {
        id: 'ss_1',
        situation: 'Your partner goes quiet after you bring up marriage.',
        statement: '"...I don\'t know. Maybe. Can we talk about something else?"',
        speaker: 'Your partner of 3 years',
        bodyLanguage: 'Avoids eye contact, fidgets with phone, shorter answers',
        surfaceEmotion: 'Avoidance / Indifference',
        hiddenEmotion: 'Fear of not being good enough for marriage',
        hiddenEmotionId: 'inadequacy',
        decoyEmotions: ['rejection', 'resentment', 'jealousy'],
        explanation: 'The shutdown isn\'t lack of interest — it\'s fear of inadequacy. "What if I\'m not a good enough partner? What if marriage exposes my flaws?" Avoidance protects against that vulnerability.',
        betterResponse: '"No pressure. I just want you to know I see a future with you. When you\'re ready to talk, I\'m here."',
      },
      {
        id: 'ss_2',
        situation: 'Your normally chatty friend becomes mono-syllabic after their breakup.',
        statement: '"I\'m fine. Really. Just tired."',
        speaker: 'Friend (recently broken up)',
        bodyLanguage: 'Forced smile, hugging themselves, looking away',
        surfaceEmotion: 'Dismissal / Minimizing',
        hiddenEmotion: 'Grief they don\'t feel safe expressing',
        hiddenEmotionId: 'grief',
        decoyEmotions: ['shame', 'fear', 'resentment'],
        explanation: '"I\'m fine" from someone in pain is a test — they\'re checking if you\'ll push past the wall. The grief feels too big and messy to share unless someone makes it safe.',
        betterResponse: '"You don\'t have to be fine with me. I\'m here whether you want to talk or just sit together."',
      },
      {
        id: 'ss_3',
        situation: 'Your employee stops contributing ideas in meetings after their project was rejected.',
        statement: '"Whatever the team decides is fine with me."',
        speaker: 'Team member',
        bodyLanguage: 'Leans back in chair, arms crossed, minimal eye contact',
        surfaceEmotion: 'Compliance / Passivity',
        hiddenEmotion: 'Shame from public rejection',
        hiddenEmotionId: 'shame',
        decoyEmotions: ['loneliness', 'helplessness', 'fear'],
        explanation: 'Withdrawal after rejection is a shame response. They interpret the project rejection as personal rejection. Contributing ideas now feels too risky.',
        betterResponse: '"I valued your thinking on the last project. The idea had merit — the timing was off. I want to hear your perspective on this."',
      },
      {
        id: 'ss_4',
        situation: 'Your mother gives you the silent treatment after you set a boundary.',
        statement: '"...I have nothing to say about that."',
        speaker: 'Your mother',
        bodyLanguage: 'Stiff posture, pressed lips, pointedly doing chores',
        surfaceEmotion: 'Coldness / Punishment',
        hiddenEmotion: 'Fear of losing control and relevance',
        hiddenEmotionId: 'fear',
        decoyEmotions: ['grief', 'jealousy', 'betrayal'],
        explanation: 'Silent treatment is often a fear response disguised as punishment. Your boundary represents a shift in the power dynamic. She fears losing influence in your life.',
        betterResponse: '"I love you, Mom. Setting this boundary isn\'t about pushing you away — it\'s about making our relationship healthier."',
      },
      {
        id: 'ss_5',
        situation: 'Your partner deflects every time you try to discuss the future.',
        statement: '"Why do we always have to plan everything? Can\'t we just enjoy right now?"',
        speaker: 'Partner',
        bodyLanguage: 'Nervous laughter, changes subject, gets up to do something',
        surfaceEmotion: 'Avoidance / Free-spirited attitude',
        hiddenEmotion: 'Fear of commitment exposing vulnerability',
        hiddenEmotionId: 'vulnerability',
        decoyEmotions: ['resentment', 'inadequacy', 'overwhelm'],
        explanation: 'The "live in the moment" philosophy masks a fear that planning means promising — and promising means potentially failing or being trapped. Commitment requires vulnerability they\'re not ready for.',
        betterResponse: '"I love being present with you. I\'m not trying to pin things down — I just want to know we\'re dreaming in the same direction."',
      },
      {
        id: 'ss_6',
        situation: 'Your friend stops inviting you to group events after you got a new partner.',
        statement: '"I figured you\'d be busy. You don\'t need us anymore."',
        speaker: 'Close friend',
        bodyLanguage: 'Shrugging, looking at phone, casual tone that doesn\'t match eyes',
        surfaceEmotion: 'Casual / Unbothered',
        hiddenEmotion: 'Fear of being replaced and losing the friendship',
        hiddenEmotionId: 'rejection',
        decoyEmotions: ['shame', 'overwhelm', 'grief'],
        explanation: '"You don\'t need us" is a preemptive rejection — they\'re withdrawing before you can leave them. Your new relationship triggers their abandonment fear.',
        betterResponse: '"I absolutely still need you in my life. Can we make a standing plan — just the two of us?"',
      },
      {
        id: 'ss_7',
        situation: 'Your colleague becomes cold after being passed over for promotion.',
        statement: '"Congratulations. You deserve it." (Flat tone, no smile)',
        speaker: 'Colleague',
        bodyLanguage: 'Handshake is brief, leaves quickly after',
        surfaceEmotion: 'Professional courtesy',
        hiddenEmotion: 'Resentment mixed with self-doubt',
        hiddenEmotionId: 'resentment',
        decoyEmotions: ['loneliness', 'fear', 'vulnerability'],
        explanation: 'The flat delivery reveals the gap between what they feel they should say and what they actually feel. They\'re battling both envy toward you and questioning their own worth.',
        betterResponse: '"Thank you. I know this must be disappointing. For what it\'s worth, I think you\'re incredibly talented and your time is coming."',
      },
      {
        id: 'ss_8',
        situation: 'Your child stops talking about school after getting a bad grade.',
        statement: '"School is boring. I don\'t care about grades."',
        speaker: 'Your child (12)',
        bodyLanguage: 'Slumped shoulders, won\'t show backpack, goes straight to room',
        surfaceEmotion: 'Apathy / Defiance',
        hiddenEmotion: 'Shame and fear of disappointing you',
        hiddenEmotionId: 'shame',
        decoyEmotions: ['helplessness', 'loneliness', 'resentment'],
        explanation: '"I don\'t care" is protective armor against the shame of failing. If they pretend not to care, the bad grade can\'t hurt. Underneath is the fear that your love is conditional on their performance.',
        betterResponse: '"Grades don\'t change how I feel about you. But I can tell something\'s going on. Want to talk about it, or just hang out?"',
      },
    ],
  },
];

export const ADVANCED_DECODER_SETS: DecoderSet[] = [
  {
    id: 'cheerful_masks',
    title: 'Cheerful Masks',
    description: 'When smiles, jokes, and enthusiasm hide something darker',
    difficulty: 2,
    cards: [
      {
        id: 'cm_1',
        situation: 'Your coworker makes constant self-deprecating jokes about their abilities.',
        statement: '"Ha! I\'m basically the team mascot at this point. Don\'t give me anything important — I\'ll just mess it up!"',
        speaker: 'Coworker',
        bodyLanguage: 'Big smile, exaggerated gestures, eyes darting to see who\'s laughing',
        surfaceEmotion: 'Self-deprecating humor / Lightheartedness',
        hiddenEmotion: 'Deep inadequacy masked by preemptive self-attack',
        hiddenEmotionId: 'inadequacy',
        decoyEmotions: ['loneliness', 'grief', 'jealousy'],
        explanation: 'By mocking themselves first, they control the narrative — if they\'re the joke, no one else can surprise them with criticism. The humor is armor against the real belief that they\'re not good enough.',
        betterResponse: '"Actually, your work on the last project was solid. I don\'t think you give yourself enough credit."',
      },
      {
        id: 'cm_2',
        situation: 'Your friend is overly enthusiastic about your new relationship.',
        statement: '"Oh my GOD I\'m SO happy for you! This is amazing! You two are PERFECT together! Tell me EVERYTHING!"',
        speaker: 'Single friend',
        bodyLanguage: 'Over-animated, gripping your arm, pitch higher than normal, smile doesn\'t reach eyes',
        surfaceEmotion: 'Excitement / Joy',
        hiddenEmotion: 'Loneliness triggered by your happiness',
        hiddenEmotionId: 'loneliness',
        decoyEmotions: ['resentment', 'fear', 'shame'],
        explanation: 'The over-the-top enthusiasm is compensation. Genuine happiness for you exists, but it\'s layered over pain about their own situation. The excessive energy tries to drown out the quiet voice asking "when is it my turn?"',
        betterResponse: '"Thanks! I appreciate that. But hey — how are YOU doing? We haven\'t really talked about your life lately."',
      },
      {
        id: 'cm_3',
        situation: 'Your colleague laughs off a serious mistake they made at work.',
        statement: '"Whoops! Classic me, right? Well, nobody died! Let\'s just pretend that never happened."',
        speaker: 'Colleague',
        bodyLanguage: 'Forced laugh, rubbing back of neck, avoiding the screen with the error',
        surfaceEmotion: 'Casual amusement / Nonchalance',
        hiddenEmotion: 'Shame spiral they\'re trying to outrun',
        hiddenEmotionId: 'shame',
        decoyEmotions: ['helplessness', 'fear', 'overwhelm'],
        explanation: 'Humor after failure is a shame-avoidance strategy. If they treat it lightly, maybe the shame won\'t land. But the neck-rubbing and avoidance reveal the internal panic. They need permission to make mistakes, not a co-conspirator in pretending it didn\'t happen.',
        betterResponse: '"Hey, mistakes happen. Let\'s fix it together. No judgment — I\'ve done worse."',
      },
      {
        id: 'cm_4',
        situation: 'Your partner is suddenly extra affectionate after a fight they caused.',
        statement: '"I made your favorite dinner! And I got you flowers. Come here, I love you so much."',
        speaker: 'Partner',
        bodyLanguage: 'Overly attentive, watching your reaction closely, tense shoulders despite smile',
        surfaceEmotion: 'Love / Warmth / Generosity',
        hiddenEmotion: 'Fear that the fight damaged the relationship irreparably',
        hiddenEmotionId: 'fear',
        decoyEmotions: ['shame', 'grief', 'vulnerability'],
        explanation: 'The love bombing after conflict is driven by fear, not just affection. They\'re not addressing the fight — they\'re trying to overwrite it with gestures. The tense shoulders reveal they\'re watching to see if you\'ve forgiven them without having to actually talk about it.',
        betterResponse: '"This is really sweet, and I appreciate it. But I think we still need to talk about what happened. The dinner doesn\'t have to fix everything."',
      },
      {
        id: 'cm_5',
        situation: 'Your friend seems incredibly upbeat about getting laid off.',
        statement: '"Honestly? Best thing that ever happened to me. I hated that place anyway. Now I can finally pursue my REAL passion!"',
        speaker: 'Friend (laid off 3 days ago)',
        bodyLanguage: 'Speaking fast, hands moving constantly, hasn\'t mentioned what the passion is',
        surfaceEmotion: 'Optimism / Relief / Excitement',
        hiddenEmotion: 'Terror about financial security and identity loss',
        hiddenEmotionId: 'fear',
        decoyEmotions: ['resentment', 'jealousy', 'shame'],
        explanation: 'The speed and energy of the "this is great" narrative is proportional to the panic underneath. Three days isn\'t enough to process a job loss — the forced optimism is a survival mechanism. Notice they can\'t name the passion because there isn\'t one yet.',
        betterResponse: '"I admire your attitude. And also — it\'s okay if some days are scary. I\'m here for the optimistic days AND the tough ones."',
      },
      {
        id: 'cm_6',
        situation: 'Your manager is overly cheerful when announcing company restructuring.',
        statement: '"This is actually GREAT news for the team! More opportunity, leaner operations. I\'m really excited about where this is headed!"',
        speaker: 'Manager',
        bodyLanguage: 'Rehearsed smile, speaking from notes, not pausing for questions',
        surfaceEmotion: 'Enthusiasm / Confidence',
        hiddenEmotion: 'Overwhelm from being forced to deliver bad news positively',
        hiddenEmotionId: 'overwhelm',
        decoyEmotions: ['fear', 'shame', 'helplessness'],
        explanation: 'Managers are often coached to frame layoffs as opportunity. The rehearsed quality and avoidance of questions reveal someone performing a script they don\'t believe. They\'re overwhelmed by the dissonance between what they feel and what they\'re required to say.',
        betterResponse: '"Thanks for the update. I know delivering this kind of news isn\'t easy either. What can the team do to make this transition smoother?"',
      },
      {
        id: 'cm_7',
        situation: 'Your friend insists they\'re "totally over" their ex while stalking their social media.',
        statement: '"I literally could not care less what they\'re doing. I\'m THRIVING. Oh — did you see they posted from that restaurant we used to go to?"',
        speaker: 'Friend (breakup 2 weeks ago)',
        bodyLanguage: 'Phone in hand, scrolling, glancing at you to gauge reaction',
        surfaceEmotion: 'Indifference / Confidence',
        hiddenEmotion: 'Grief they haven\'t allowed themselves to feel',
        hiddenEmotionId: 'grief',
        decoyEmotions: ['jealousy', 'resentment', 'vulnerability'],
        explanation: 'The contradiction between "I don\'t care" and monitoring every post reveals unprocessed grief. Performing indifference feels safer than admitting they\'re heartbroken. The restaurant mention is the grief leaking through the performance.',
        betterResponse: '"It\'s okay to miss them. Being over someone doesn\'t happen on a schedule. What do you actually feel right now?"',
      },
      {
        id: 'cm_8',
        situation: 'Your colleague is aggressively positive about doing extra work after others quit.',
        statement: '"More for me! I love staying busy. Honestly, I do my best work under pressure. Bring it on!"',
        speaker: 'Colleague (absorbing work of 2 people who quit)',
        bodyLanguage: 'Dark circles, third coffee, desk covered in sticky notes, leg bouncing',
        surfaceEmotion: 'Enthusiasm / Resilience',
        hiddenEmotion: 'Resentment at being exploited, fear of saying no',
        hiddenEmotionId: 'resentment',
        decoyEmotions: ['inadequacy', 'loneliness', 'grief'],
        explanation: 'The toxic positivity about an unsustainable workload masks deep resentment. They\'ve learned that complaining is career-dangerous, so they perform enthusiasm while burning out. The physical signs (coffee, circles, bouncing leg) betray the truth.',
        betterResponse: '"You\'re doing an incredible job handling all of this. But honestly — is this sustainable? It\'s okay to say it\'s too much."',
      },
    ],
  },
  {
    id: 'overcompensation',
    title: 'Overcompensation',
    description: 'When people do too much of one thing to hide the opposite',
    difficulty: 3,
    cards: [
      {
        id: 'oc_1',
        situation: 'A new hire dominates every meeting with aggressive confidence.',
        statement: '"I actually led a project exactly like this at my last company. Here\'s how we should do it — I\'ve seen what works."',
        speaker: 'New team member (1 week in)',
        bodyLanguage: 'Leaning forward, cutting others off, name-dropping previous company',
        surfaceEmotion: 'Confidence / Assertiveness',
        hiddenEmotion: 'Imposter syndrome — terrified of being exposed',
        hiddenEmotionId: 'fear',
        decoyEmotions: ['resentment', 'jealousy', 'shame'],
        explanation: 'Overconfidence in a new environment is almost always imposter syndrome in disguise. They\'re performing competence so aggressively because they\'re terrified that silence will be read as incompetence. The name-dropping anchors their value to past identity.',
        betterResponse: '"Your experience sounds valuable. We also have some context that might be different here — let\'s compare notes."',
      },
      {
        id: 'oc_2',
        situation: 'Your friend suddenly posts daily gym selfies after their partner left them.',
        statement: '"New year, new me! Six months of grinding and look at these results. Best shape of my life. Living my best life."',
        speaker: 'Friend (recently divorced)',
        bodyLanguage: 'Flexing in photos, filters on everything, posting at 5am',
        surfaceEmotion: 'Pride / Self-improvement / Empowerment',
        hiddenEmotion: 'Desperate attempt to rebuild shattered self-worth',
        hiddenEmotionId: 'inadequacy',
        decoyEmotions: ['grief', 'loneliness', 'fear'],
        explanation: 'The revenge glow-up is a legitimate coping mechanism, but the intensity reveals the wound. Constant public documentation seeks external validation to fill the void left by the person who was supposed to make them feel worthy. The 5am posts signal someone who can\'t sleep.',
        betterResponse: '"You look great and I\'m glad you\'re taking care of yourself. How are you REALLY doing though? The inside stuff?"',
      },
      {
        id: 'oc_3',
        situation: 'Your manager micromanages every detail of your project.',
        statement: '"I need to see all drafts before they go out. CC me on every email. And let\'s do daily check-ins instead of weekly."',
        speaker: 'Manager',
        bodyLanguage: 'Rigid posture, checking their phone constantly, interrupting to correct minor details',
        surfaceEmotion: 'Thoroughness / Dedication',
        hiddenEmotion: 'Fear of failure and loss of control',
        hiddenEmotionId: 'fear',
        decoyEmotions: ['resentment', 'jealousy', 'overwhelm'],
        explanation: 'Micromanagement is never about your competence — it\'s about their anxiety. Something in their past (a project that failed, a boss who punished mistakes) created a belief that control prevents catastrophe. Every detail they check is a tiny hit of anxiety relief.',
        betterResponse: '"I want you to feel confident in the output. What if I sent you a brief daily summary so you have visibility without needing to review every draft?"',
      },
      {
        id: 'oc_4',
        situation: 'Your friend one-ups every story with a bigger version of their own.',
        statement: '"Oh you went to Spain? That\'s cool. We did three weeks in Southeast Asia last year. Totally life-changing. You should really try going somewhere more adventurous."',
        speaker: 'Friend',
        bodyLanguage: 'Leaning in when telling their story, leaning back during yours, scanning for audience reaction',
        surfaceEmotion: 'Enthusiasm / Adventurousness',
        hiddenEmotion: 'Deep insecurity about their own significance',
        hiddenEmotionId: 'inadequacy',
        decoyEmotions: ['jealousy', 'helplessness', 'loneliness'],
        explanation: 'Compulsive one-upping reveals someone who can\'t let others shine without feeling diminished. Every story of yours triggers the fear that they\'re ordinary. They\'re not trying to impress you — they\'re trying to reassure themselves.',
        betterResponse: '"That sounds amazing! What was the most meaningful part of that trip for you?"',
      },
      {
        id: 'oc_5',
        situation: 'A colleague volunteers for every task and never says no.',
        statement: '"I\'ll handle the report, the presentation, AND the client call. No worries, I\'ve got it all covered! Don\'t even think about it."',
        speaker: 'Colleague',
        bodyLanguage: 'Already looking stressed, email inbox overflowing, eating lunch at desk',
        surfaceEmotion: 'Generosity / Team spirit',
        hiddenEmotion: 'Fear that saying no will make them dispensable',
        hiddenEmotionId: 'fear',
        decoyEmotions: ['shame', 'resentment', 'overwhelm'],
        explanation: 'Performative generosity at work often masks a survival strategy: if I\'m indispensable, I\'m safe. The inability to say no isn\'t kindness — it\'s a fear that their value is measured only in output, not in who they are.',
        betterResponse: '"I appreciate you stepping up, but I want to make sure we\'re not burning you out. Let\'s split this up — which piece do you actually want?"',
      },
      {
        id: 'oc_6',
        situation: 'Someone you just met shares extremely personal information immediately.',
        statement: '"So yeah, my parents\' divorce really messed me up. I\'ve been in therapy for three years. I have an anxious attachment style. I just believe in being totally open, you know?"',
        speaker: 'New acquaintance (met 10 minutes ago)',
        bodyLanguage: 'Intense eye contact, talking fast, leaning in close, monitoring your reaction',
        surfaceEmotion: 'Openness / Vulnerability / Authenticity',
        hiddenEmotion: 'Desperate need for connection, testing if you\'ll stay',
        hiddenEmotionId: 'loneliness',
        decoyEmotions: ['grief', 'shame', 'vulnerability'],
        explanation: 'Premature vulnerability is a connection shortcut — they\'re trying to fast-track intimacy because they fear the slow build won\'t hold. It\'s a test: "If I show you the worst parts now, will you still be here?" The monitoring reveals the anxiety behind the "openness."',
        betterResponse: '"I appreciate you sharing that. I\'d love to get to know you better — let\'s grab coffee sometime and keep talking."',
      },
      {
        id: 'oc_7',
        situation: 'Your friend loudly insists they don\'t care about social media while clearly curating their image.',
        statement: '"I honestly never check my likes or followers. Social media is so toxic. I only post for myself."',
        speaker: 'Friend (who deletes posts under 50 likes)',
        bodyLanguage: 'Checking phone notifications while saying this, previously asked you to like their post',
        surfaceEmotion: 'Above-it-all detachment',
        hiddenEmotion: 'Shame about needing external validation',
        hiddenEmotionId: 'shame',
        decoyEmotions: ['fear', 'inadequacy', 'resentment'],
        explanation: 'The louder someone proclaims indifference to something, the more power it has over them. The performance of not caring is itself a form of caring. They\'re ashamed that likes matter to them because they believe they shouldn\'t.',
        betterResponse: '"It\'s honestly pretty normal to care about how you\'re perceived. Nothing wrong with wanting people to appreciate what you share."',
      },
      {
        id: 'oc_8',
        situation: 'Your colleague becomes aggressively competitive after you both apply for the same role.',
        statement: '"May the best person win! Honestly, I think the competition will bring out the best in both of us. I\'ve already started prepping my portfolio."',
        speaker: 'Colleague / competitor',
        bodyLanguage: 'Working late conspicuously, mentioning their prep casually, laughing too loudly at the boss\'s jokes',
        surfaceEmotion: 'Sportsmanship / Confidence',
        hiddenEmotion: 'Terror of losing and what that would mean about their worth',
        hiddenEmotionId: 'fear',
        decoyEmotions: ['jealousy', 'resentment', 'shame'],
        explanation: 'The aggressive sportsmanship masks existential fear. They\'re not just competing for a role — they\'re competing against the possibility of being "not chosen." The conspicuous preparation and boss-flattery are anxiety-driven, not strategy-driven.',
        betterResponse: '"Whatever happens, I respect your work and hope we can both keep supporting each other regardless of the outcome."',
      },
    ],
  },
];

DECODER_SETS.push(...ADVANCED_DECODER_SETS);

export function getDecoderSetById(id: string): DecoderSet | undefined {
  return DECODER_SETS.find((s) => s.id === id);
}
