export interface DecoderSet {
  id: string;
  title: string;
  description: string;
  difficulty: number;
  cards: DecoderCard[];
}

export interface DecoderCard {
  id: string;
  situation: string;
  statement: string;
  speaker: string;
  bodyLanguage: string;
  surfaceEmotion: string;
  hiddenEmotion: string;
  hiddenEmotionId: string;
  decoyEmotions: string[];
  explanation: string;
  betterResponse: string;
}

export const EMOTION_OPTIONS = [
  { id: 'fear', label: 'Fear', icon: 'alert-circle-outline', color: '#D29922' },
  { id: 'shame', label: 'Shame', icon: 'eye-off-outline', color: '#7B2D8E' },
  { id: 'loneliness', label: 'Loneliness', icon: 'account-off-outline', color: '#7B68EE' },
  { id: 'grief', label: 'Grief', icon: 'heart-broken-outline', color: '#45B7D1' },
  { id: 'inadequacy', label: 'Inadequacy', icon: 'thumb-down-outline', color: '#4A5568' },
  { id: 'rejection', label: 'Rejection', icon: 'account-remove-outline', color: '#D93025' },
  { id: 'helplessness', label: 'Helplessness', icon: 'hand-back-left-outline', color: '#8B949E' },
  { id: 'jealousy', label: 'Jealousy', icon: 'eye-outline', color: '#2EA043' },
  { id: 'betrayal', label: 'Betrayal', icon: 'shield-off-outline', color: '#F85149' },
  { id: 'overwhelm', label: 'Overwhelm', icon: 'waves', color: '#FF8C42' },
  { id: 'resentment', label: 'Resentment', icon: 'thought-bubble-outline', color: '#8B6914' },
  { id: 'vulnerability', label: 'Vulnerability', icon: 'shield-alert-outline', color: '#FF69B4' },
];

export const DECODER_SETS: DecoderSet[] = [
  {
    id: 'anger_beneath',
    title: 'What\'s Behind the Anger',
    description: 'Decode what people really feel when they express anger',
    difficulty: 2,
    cards: [
      {
        id: 'ab_1',
        situation: 'Your teenage daughter slams the door and yells "I hate this family!"',
        statement: '"I HATE this family! Nobody ever listens to me! I wish I could just leave!"',
        speaker: 'Your daughter (15)',
        bodyLanguage: 'Tears in eyes, clenched fists, voice cracking',
        surfaceEmotion: 'Anger / Rage',
        hiddenEmotion: 'Helplessness',
        hiddenEmotionId: 'helplessness',
        decoyEmotions: ['jealousy', 'shame', 'betrayal'],
        explanation: 'The explosive anger masks a deep sense of powerlessness. She doesn\'t feel heard or valued, and the only way she knows to express that is through intensity. The tears and cracking voice reveal the vulnerability underneath.',
        betterResponse: '"I can see you\'re really hurting right now. I want to hear what\'s going on. Can we talk when you\'re ready?"',
      },
      {
        id: 'ab_2',
        situation: 'Your partner snaps at you for not doing the dishes.',
        statement: '"Why can\'t you just DO things without me having to ASK? I\'m not your mother!"',
        speaker: 'Your partner',
        bodyLanguage: 'Arms crossed, won\'t make eye contact, jaw tight',
        surfaceEmotion: 'Frustration / Contempt',
        hiddenEmotion: 'Feeling invisible and undervalued',
        hiddenEmotionId: 'inadequacy',
        decoyEmotions: ['jealousy', 'grief', 'betrayal'],
        explanation: 'The dishes are a proxy. Underneath the anger is a feeling of being taken for granted — that their contributions go unnoticed while they\'re expected to manage everything. They feel more like a caretaker than an equal partner.',
        betterResponse: '"You\'re right that I should be more proactive. I think this is about more than dishes — are you feeling like things aren\'t balanced?"',
      },
      {
        id: 'ab_3',
        situation: 'Your friend aggressively criticizes your new hobby.',
        statement: '"Pottery? Really? That\'s the most pointless thing I\'ve ever heard. What a waste of time."',
        speaker: 'Your friend',
        bodyLanguage: 'Nervous laugh, scrolling phone, dismissive hand wave',
        surfaceEmotion: 'Mockery / Disdain',
        hiddenEmotion: 'Jealousy',
        hiddenEmotionId: 'jealousy',
        decoyEmotions: ['helplessness', 'shame', 'loneliness'],
        explanation: 'When someone aggressively mocks your growth, they often feel threatened by it. Your new interest highlights that they\'re not pursuing anything meaningful, triggering envy disguised as contempt.',
        betterResponse: '"Seems like that hit a nerve. I\'d love it if you tried it with me sometime."',
      },
      {
        id: 'ab_4',
        situation: 'Your coworker angrily confronts you about going to lunch without them.',
        statement: '"Thanks for the invite. Oh wait, I didn\'t get one. Good to know where I stand with this team."',
        speaker: 'Coworker',
        bodyLanguage: 'Fake smile, stiff posture, speaking louder than necessary',
        surfaceEmotion: 'Sarcasm / Passive aggression',
        hiddenEmotion: 'Fear of being excluded and rejected',
        hiddenEmotionId: 'rejection',
        decoyEmotions: ['resentment', 'shame', 'overwhelm'],
        explanation: 'The sarcasm is armor. Underneath is a genuine fear of not belonging. Saying "I feel left out" feels too vulnerable, so they weaponize it instead.',
        betterResponse: '"I\'m sorry we didn\'t ask — it wasn\'t intentional. You\'re always welcome. Want to grab coffee this afternoon?"',
      },
      {
        id: 'ab_5',
        situation: 'Your father blows up when you mention visiting less often.',
        statement: '"Fine! Don\'t bother coming at all then. I managed alone before you were born, I can manage again!"',
        speaker: 'Your father (68)',
        bodyLanguage: 'Turns away, voice rises then drops, hand on forehead',
        surfaceEmotion: 'Defiance / Pride',
        hiddenEmotion: 'Fear of abandonment and loneliness',
        hiddenEmotionId: 'loneliness',
        decoyEmotions: ['shame', 'inadequacy', 'resentment'],
        explanation: 'The "I don\'t need you" posture is a protective mechanism against the terror of being alone. Aging + reduced visits triggers abandonment fear. He pushes away before he can be left behind.',
        betterResponse: '"I\'m not going anywhere, Dad. I love you. Let\'s figure out a schedule that works for both of us."',
      },
      {
        id: 'ab_6',
        situation: 'Your sibling accuses you of being the "favorite child."',
        statement: '"Of course Mom calls you first. You\'ve always been the golden child. Must be nice."',
        speaker: 'Your sibling',
        bodyLanguage: 'Staring at the floor, picking at fingernails, bitter tone',
        surfaceEmotion: 'Resentment / Bitterness',
        hiddenEmotion: 'Feeling inadequate and unseen',
        hiddenEmotionId: 'inadequacy',
        decoyEmotions: ['betrayal', 'loneliness', 'fear'],
        explanation: 'The accusation of favoritism reflects a lifelong wound of feeling "not enough." They\'re not actually angry at you — they\'re grieving the parental validation they never felt they received.',
        betterResponse: '"I hear you. I know Mom and I are close, but that doesn\'t mean she doesn\'t love you. How are you feeling about your relationship with her?"',
      },
      {
        id: 'ab_7',
        situation: 'A client furiously demands a refund over a minor issue.',
        statement: '"This is COMPLETELY unacceptable! I\'ve been a customer for TEN YEARS and this is how you treat me?!"',
        speaker: 'Long-time client',
        bodyLanguage: 'Red face, leaning forward, finger pointing',
        surfaceEmotion: 'Outrage / Indignation',
        hiddenEmotion: 'Feeling disrespected and undervalued',
        hiddenEmotionId: 'rejection',
        decoyEmotions: ['overwhelm', 'grief', 'jealousy'],
        explanation: 'The disproportionate reaction reveals that this isn\'t about the minor issue — it\'s about feeling like their loyalty doesn\'t matter. They need to feel seen and valued, not just serviced.',
        betterResponse: '"Ten years means a lot to us, and you deserve better than this. Let me make it right personally."',
      },
      {
        id: 'ab_8',
        situation: 'Your partner explodes after you get a job offer in another city.',
        statement: '"So you just decided for both of us?! What about what I want? Do I even matter?"',
        speaker: 'Partner',
        bodyLanguage: 'Pacing, hands through hair, voice shaking',
        surfaceEmotion: 'Anger / Betrayal',
        hiddenEmotion: 'Fear of losing the relationship',
        hiddenEmotionId: 'fear',
        decoyEmotions: ['resentment', 'shame', 'helplessness'],
        explanation: 'The anger is a response to a perceived threat to the relationship. "Do I even matter?" reveals the core fear — that you\'d choose career over them. They need reassurance of their importance.',
        betterResponse: '"You absolutely matter. I haven\'t decided anything — I want to figure this out together. What are your fears?"',
      },
    ],
  },
  {
    id: 'silence_speaks',
    title: 'When Silence Speaks',
    description: 'Decode withdrawal, avoidance, and emotional shutdowns',
    difficulty: 3,
    cards: [
      {
        id: 'ss_1',
        situation: 'Your partner goes quiet after you bring up marriage.',
        statement: '"...I don\'t know. Maybe. Can we talk about something else?"',
        speaker: 'Your partner of 3 years',
        bodyLanguage: 'Avoids eye contact, fidgets with phone, shorter answers',
        surfaceEmotion: 'Avoidance / Indifference',
        hiddenEmotion: 'Fear of not being good enough for marriage',
        hiddenEmotionId: 'inadequacy',
        decoyEmotions: ['rejection', 'resentment', 'jealousy'],
        explanation: 'The shutdown isn\'t lack of interest — it\'s fear of inadequacy. "What if I\'m not a good enough partner? What if marriage exposes my flaws?" Avoidance protects against that vulnerability.',
        betterResponse: '"No pressure. I just want you to know I see a future with you. When you\'re ready to talk, I\'m here."',
      },
      {
        id: 'ss_2',
        situation: 'Your normally chatty friend becomes mono-syllabic after their breakup.',
        statement: '"I\'m fine. Really. Just tired."',
        speaker: 'Friend (recently broken up)',
        bodyLanguage: 'Forced smile, hugging themselves, looking away',
        surfaceEmotion: 'Dismissal / Minimizing',
        hiddenEmotion: 'Grief they don\'t feel safe expressing',
        hiddenEmotionId: 'grief',
        decoyEmotions: ['shame', 'fear', 'resentment'],
        explanation: '"I\'m fine" from someone in pain is a test — they\'re checking if you\'ll push past the wall. The grief feels too big and messy to share unless someone makes it safe.',
        betterResponse: '"You don\'t have to be fine with me. I\'m here whether you want to talk or just sit together."',
      },
      {
        id: 'ss_3',
        situation: 'Your employee stops contributing ideas in meetings after their project was rejected.',
        statement: '"Whatever the team decides is fine with me."',
        speaker: 'Team member',
        bodyLanguage: 'Leans back in chair, arms crossed, minimal eye contact',
        surfaceEmotion: 'Compliance / Passivity',
        hiddenEmotion: 'Shame from public rejection',
        hiddenEmotionId: 'shame',
        decoyEmotions: ['loneliness', 'helplessness', 'fear'],
        explanation: 'Withdrawal after rejection is a shame response. They interpret the project rejection as personal rejection. Contributing ideas now feels too risky.',
        betterResponse: '"I valued your thinking on the last project. The idea had merit — the timing was off. I want to hear your perspective on this."',
      },
      {
        id: 'ss_4',
        situation: 'Your mother gives you the silent treatment after you set a boundary.',
        statement: '"...I have nothing to say about that."',
        speaker: 'Your mother',
        bodyLanguage: 'Stiff posture, pressed lips, pointedly doing chores',
        surfaceEmotion: 'Coldness / Punishment',
        hiddenEmotion: 'Fear of losing control and relevance',
        hiddenEmotionId: 'fear',
        decoyEmotions: ['grief', 'jealousy', 'betrayal'],
        explanation: 'Silent treatment is often a fear response disguised as punishment. Your boundary represents a shift in the power dynamic. She fears losing influence in your life.',
        betterResponse: '"I love you, Mom. Setting this boundary isn\'t about pushing you away — it\'s about making our relationship healthier."',
      },
      {
        id: 'ss_5',
        situation: 'Your partner deflects every time you try to discuss the future.',
        statement: '"Why do we always have to plan everything? Can\'t we just enjoy right now?"',
        speaker: 'Partner',
        bodyLanguage: 'Nervous laughter, changes subject, gets up to do something',
        surfaceEmotion: 'Avoidance / Free-spirited attitude',
        hiddenEmotion: 'Fear of commitment exposing vulnerability',
        hiddenEmotionId: 'vulnerability',
        decoyEmotions: ['resentment', 'inadequacy', 'overwhelm'],
        explanation: 'The "live in the moment" philosophy masks a fear that planning means promising — and promising means potentially failing or being trapped. Commitment requires vulnerability they\'re not ready for.',
        betterResponse: '"I love being present with you. I\'m not trying to pin things down — I just want to know we\'re dreaming in the same direction."',
      },
      {
        id: 'ss_6',
        situation: 'Your friend stops inviting you to group events after you got a new partner.',
        statement: '"I figured you\'d be busy. You don\'t need us anymore."',
        speaker: 'Close friend',
        bodyLanguage: 'Shrugging, looking at phone, casual tone that doesn\'t match eyes',
        surfaceEmotion: 'Casual / Unbothered',
        hiddenEmotion: 'Fear of being replaced and losing the friendship',
        hiddenEmotionId: 'rejection',
        decoyEmotions: ['shame', 'overwhelm', 'grief'],
        explanation: '"You don\'t need us" is a preemptive rejection — they\'re withdrawing before you can leave them. Your new relationship triggers their abandonment fear.',
        betterResponse: '"I absolutely still need you in my life. Can we make a standing plan — just the two of us?"',
      },
      {
        id: 'ss_7',
        situation: 'Your colleague becomes cold after being passed over for promotion.',
        statement: '"Congratulations. You deserve it." (Flat tone, no smile)',
        speaker: 'Colleague',
        bodyLanguage: 'Handshake is brief, leaves quickly after',
        surfaceEmotion: 'Professional courtesy',
        hiddenEmotion: 'Resentment mixed with self-doubt',
        hiddenEmotionId: 'resentment',
        decoyEmotions: ['loneliness', 'fear', 'vulnerability'],
        explanation: 'The flat delivery reveals the gap between what they feel they should say and what they actually feel. They\'re battling both envy toward you and questioning their own worth.',
        betterResponse: '"Thank you. I know this must be disappointing. For what it\'s worth, I think you\'re incredibly talented and your time is coming."',
      },
      {
        id: 'ss_8',
        situation: 'Your child stops talking about school after getting a bad grade.',
        statement: '"School is boring. I don\'t care about grades."',
        speaker: 'Your child (12)',
        bodyLanguage: 'Slumped shoulders, won\'t show backpack, goes straight to room',
        surfaceEmotion: 'Apathy / Defiance',
        hiddenEmotion: 'Shame and fear of disappointing you',
        hiddenEmotionId: 'shame',
        decoyEmotions: ['helplessness', 'loneliness', 'resentment'],
        explanation: '"I don\'t care" is protective armor against the shame of failing. If they pretend not to care, the bad grade can\'t hurt. Underneath is the fear that your love is conditional on their performance.',
        betterResponse: '"Grades don\'t change how I feel about you. But I can tell something\'s going on. Want to talk about it, or just hang out?"',
      },
    ],
  },
];

export function getDecoderSetById(id: string): DecoderSet | undefined {
  return DECODER_SETS.find((s) => s.id === id);
}
