export interface FirstResponseSet {
  id: string;
  title: string;
  description: string;
  difficulty: number;
  rounds: FirstResponseRound[];
}

export interface FirstResponseRound {
  id: string;
  provocation: string;
  speaker: string;
  context: string;
  timeLimitMs: number;
  strategies: ResponseStrategy[];
  correctStrategyId: string;
  idealResponse: string;
  explanation: string;
}

export interface ResponseStrategy {
  id: string;
  label: string;
  description: string;
  icon: string;
}

export const FIRST_RESPONSE_SETS: FirstResponseSet[] = [
  {
    id: 'heated_moments',
    title: 'Heated Moments',
    description: 'Choose the right opening move when emotions run high',
    difficulty: 2,
    rounds: [
      {
        id: 'hm_1',
        provocation: '"You NEVER listen to me! I\'m done trying to explain myself!"',
        speaker: 'Partner',
        context: 'Recurring argument about household responsibilities',
        timeLimitMs: 15000,
        strategies: [
          { id: 'hm_1_mirror', label: 'Mirror', description: 'Reflect back what they said to show you heard them', icon: 'mirror' },
          { id: 'hm_1_defend', label: 'Defend', description: 'Explain why their accusation is wrong', icon: 'shield' },
          { id: 'hm_1_label', label: 'Label the Emotion', description: 'Name what they\'re feeling underneath the anger', icon: 'heart-pulse' },
          { id: 'hm_1_counter', label: 'Counter-Attack', description: 'Point out what they do wrong too', icon: 'sword' },
        ],
        correctStrategyId: 'hm_1_label',
        idealResponse: '"It sounds like you feel really unheard, and that\'s exhausting. I don\'t want that for us."',
        explanation: 'When someone says "you never listen," they\'re expressing emotional pain, not requesting debate. Labeling the emotion ("you feel unheard") de-escalates by showing you understand the feeling, not just the words.',
      },
      {
        id: 'hm_2',
        provocation: '"This is the worst service I\'ve ever experienced. I want to speak to your manager. NOW."',
        speaker: 'Angry customer',
        context: 'Their order was delayed by 20 minutes',
        timeLimitMs: 12000,
        strategies: [
          { id: 'hm_2_explain', label: 'Explain', description: 'Tell them why the delay happened', icon: 'information' },
          { id: 'hm_2_validate', label: 'Validate + Act', description: 'Acknowledge their frustration and take immediate action', icon: 'check-circle' },
          { id: 'hm_2_policy', label: 'Cite Policy', description: 'Explain the company\'s policy on delays', icon: 'file-document' },
          { id: 'hm_2_escalate', label: 'Escalate', description: 'Immediately get the manager', icon: 'arrow-up' },
        ],
        correctStrategyId: 'hm_2_validate',
        idealResponse: '"You\'re right to be frustrated — a 20-minute wait is too long. Let me fix this right now."',
        explanation: 'Explaining or citing policy feels like dismissal when someone is angry. Validate first, then act. The combination of "you\'re right" + immediate action usually disarms the escalation.',
      },
      {
        id: 'hm_3',
        provocation: '"You\'re being selfish. Everything is always about what YOU want."',
        speaker: 'Friend',
        context: 'You declined their invitation for the second time this month',
        timeLimitMs: 15000,
        strategies: [
          { id: 'hm_3_apologize', label: 'Apologize', description: 'Say sorry to defuse the situation', icon: 'hand-wave' },
          { id: 'hm_3_curious', label: 'Get Curious', description: 'Ask what\'s really going on for them', icon: 'head-question' },
          { id: 'hm_3_boundary', label: 'Hold Boundary', description: 'Reaffirm your right to say no', icon: 'shield-check' },
          { id: 'hm_3_match', label: 'Match Energy', description: 'Tell them they\'re being unfair', icon: 'flash' },
        ],
        correctStrategyId: 'hm_3_curious',
        idealResponse: '"That\'s a strong word. Help me understand — is this about tonight, or is something bigger going on?"',
        explanation: '"Selfish" is often a protest word that means "I feel unimportant to you." Getting curious about the real feeling prevents you from either caving (apologizing when you shouldn\'t) or escalating (defending your right to say no).',
      },
      {
        id: 'hm_4',
        provocation: '"I don\'t think you\'re ready for this promotion. Maybe in a year or two."',
        speaker: 'Manager',
        context: 'Annual review — you were expecting the promotion',
        timeLimitMs: 15000,
        strategies: [
          { id: 'hm_4_accept', label: 'Accept Quietly', description: 'Nod and plan to prove them wrong', icon: 'check' },
          { id: 'hm_4_calibrate', label: 'Calibrated Question', description: 'Ask a question that makes them think deeper', icon: 'target' },
          { id: 'hm_4_emotional', label: 'Show Disappointment', description: 'Express how let down you feel', icon: 'emoticon-sad' },
          { id: 'hm_4_threaten', label: 'Leverage', description: 'Mention other opportunities you\'re considering', icon: 'exit-run' },
        ],
        correctStrategyId: 'hm_4_calibrate',
        idealResponse: '"What would I need to demonstrate in the next quarter for you to feel confident in promoting me?"',
        explanation: 'Calibrated questions (what/how) put the other person to work solving your problem. This question makes your manager commit to specific criteria — turning a vague rejection into a concrete roadmap.',
      },
      {
        id: 'hm_5',
        provocation: '"If you leave me, I\'ll have nothing to live for."',
        speaker: 'Partner',
        context: 'You brought up concerns about the relationship',
        timeLimitMs: 15000,
        strategies: [
          { id: 'hm_5_stay', label: 'Reassure', description: 'Promise not to leave to calm them down', icon: 'hand-heart' },
          { id: 'hm_5_name', label: 'Name the Pattern', description: 'Point out that this is emotional manipulation', icon: 'alert' },
          { id: 'hm_5_care', label: 'Care + Boundary', description: 'Show compassion while not accepting responsibility for their wellbeing', icon: 'shield-heart' },
          { id: 'hm_5_ignore', label: 'Ignore It', description: 'Continue with what you were saying', icon: 'skip-forward' },
        ],
        correctStrategyId: 'hm_5_care',
        idealResponse: '"I care about you deeply, and what you\'re saying worries me. Your wellbeing matters — can we talk about getting you support?"',
        explanation: 'This is emotional crisis, not a negotiation. Don\'t promise to stay (enabling), call it manipulation (escalating), or ignore it (dangerous). Express genuine care while redirecting to professional support.',
      },
      {
        id: 'hm_6',
        provocation: '"You know what your problem is? You think you\'re smarter than everyone else."',
        speaker: 'Sibling',
        context: 'Family dinner after you corrected a factual error they made',
        timeLimitMs: 12000,
        strategies: [
          { id: 'hm_6_deflect', label: 'Deflect with Humor', description: 'Make a self-deprecating joke to lighten the mood', icon: 'emoticon-wink' },
          { id: 'hm_6_validate', label: 'Validate', description: 'Acknowledge their feeling even if you disagree with the framing', icon: 'heart' },
          { id: 'hm_6_correct', label: 'Correct', description: 'Explain that you were just sharing a fact', icon: 'book-open' },
          { id: 'hm_6_attack', label: 'Return Fire', description: 'Point out their insecurities', icon: 'fire' },
        ],
        correctStrategyId: 'hm_6_validate',
        idealResponse: '"I can see how that came across. That wasn\'t my intent. I value your perspective."',
        explanation: 'Personal attacks at family events are usually old wounds talking. Validating their perception (even if unfair) defuses the moment. Being "right" at dinner is never worth the family damage.',
      },
      {
        id: 'hm_7',
        provocation: '"I\'m fine." (Said with clenched jaw and watery eyes)',
        speaker: 'Close friend',
        context: 'You asked how they\'re doing after their parent\'s health scare',
        timeLimitMs: 15000,
        strategies: [
          { id: 'hm_7_accept', label: 'Accept It', description: 'Take their word for it and move on', icon: 'check' },
          { id: 'hm_7_push', label: 'Push Harder', description: 'Say "No you\'re not, tell me what\'s wrong"', icon: 'arrow-right-bold' },
          { id: 'hm_7_door', label: 'Leave the Door Open', description: 'Acknowledge + give permission without pushing', icon: 'door-open' },
          { id: 'hm_7_fix', label: 'Try to Fix', description: 'Start offering solutions and resources', icon: 'wrench' },
        ],
        correctStrategyId: 'hm_7_door',
        idealResponse: '"Okay. I\'m here whenever, no judgment. You don\'t have to carry this alone."',
        explanation: '"I\'m fine" when clearly not fine is a boundary test. Pushing past it feels invasive. Accepting it feels uncaring. The middle path: acknowledge gently and leave an open door. Let them choose when to walk through it.',
      },
      {
        id: 'hm_8',
        provocation: '"We need to cut your team\'s budget by 30%. Non-negotiable."',
        speaker: 'VP',
        context: 'Surprise budget meeting, your projects are at stake',
        timeLimitMs: 12000,
        strategies: [
          { id: 'hm_8_comply', label: 'Comply', description: 'Accept the cut and figure out how to make it work', icon: 'check-circle' },
          { id: 'hm_8_impact', label: 'Quantify Impact', description: 'Ask what outcomes they\'re willing to sacrifice', icon: 'chart-bar' },
          { id: 'hm_8_plead', label: 'Plead Your Case', description: 'List everything your team has accomplished', icon: 'text-box' },
          { id: 'hm_8_refuse', label: 'Refuse', description: 'Say you can\'t operate under those constraints', icon: 'close-circle' },
        ],
        correctStrategyId: 'hm_8_impact',
        idealResponse: '"I understand the need for cuts. Help me understand — which deliverables are you comfortable deprioritizing with a 30% reduction?"',
        explanation: 'Never fight the number — fight the scope. Making them choose what to cut forces them to confront the real cost of the decision. Often this reveals the cut is too deep, or at least gives you negotiating room.',
      },
    ],
  },
  {
    id: 'manipulation_defense',
    title: 'Manipulation Defense',
    description: 'Pick the right counter-move when someone tries to manipulate you',
    difficulty: 3,
    rounds: [
      {
        id: 'md_1',
        provocation: '"After everything I\'ve done for you, this is how you repay me?"',
        speaker: 'Parent',
        context: 'You chose a career path they disapprove of',
        timeLimitMs: 15000,
        strategies: [
          { id: 'md_1_guilt', label: 'Accept the Guilt', description: 'Acknowledge their sacrifices and reconsider', icon: 'hand-heart' },
          { id: 'md_1_separate', label: 'Separate + Affirm', description: 'Distinguish their love from your choices', icon: 'vector-difference' },
          { id: 'md_1_deflect', label: 'Deflect', description: 'Change the subject', icon: 'arrow-u-right-top' },
          { id: 'md_1_confront', label: 'Confront', description: 'Call out the guilt trip directly', icon: 'alert-circle' },
        ],
        correctStrategyId: 'md_1_separate',
        idealResponse: '"I\'m grateful for everything you\'ve given me. My career choice isn\'t a rejection of you — it\'s me building on what you taught me."',
        explanation: 'The guilt trip frames your independence as betrayal. The antidote is separating love from compliance. You can honor their investment AND choose your own path. These aren\'t contradictions.',
      },
      {
        id: 'md_2',
        provocation: '"Everyone else on the team is fine with working weekends. Are you not a team player?"',
        speaker: 'Manager',
        context: 'You pushed back on weekend work for the third time',
        timeLimitMs: 12000,
        strategies: [
          { id: 'md_2_comply', label: 'Comply', description: 'Agree to work the weekend to prove yourself', icon: 'check' },
          { id: 'md_2_reframe', label: 'Reframe', description: 'Redirect from loyalty to productivity', icon: 'refresh' },
          { id: 'md_2_argue', label: 'Argue', description: 'Tell them that\'s not fair', icon: 'message-alert' },
          { id: 'md_2_report', label: 'Report', description: 'Go to HR about the pressure', icon: 'flag' },
        ],
        correctStrategyId: 'md_2_reframe',
        idealResponse: '"I\'m committed to the team. I\'m also committed to delivering my best work, which requires rest. What can I reprioritize to hit our deadline during regular hours?"',
        explanation: 'The manipulation tactic here is false framing: weekend work = team player. Reframe it: sustained quality work = real team player. Then offer a concrete alternative.',
      },
      {
        id: 'md_3',
        provocation: '"I\'m not sure you could do better than me. You should feel lucky to have someone who puts up with you."',
        speaker: 'Partner',
        context: 'You mentioned feeling unhappy in the relationship',
        timeLimitMs: 15000,
        strategies: [
          { id: 'md_3_agree', label: 'Agree', description: 'Maybe they\'re right — lower your expectations', icon: 'trending-down' },
          { id: 'md_3_name', label: 'Name What\'s Happening', description: 'Identify this as a diminishing tactic', icon: 'eye' },
          { id: 'md_3_leave', label: 'Walk Away', description: 'End the conversation immediately', icon: 'exit-run' },
          { id: 'md_3_fight', label: 'Fight Back', description: 'Tell them all the things wrong with them', icon: 'sword-cross' },
        ],
        correctStrategyId: 'md_3_name',
        idealResponse: '"What I\'m hearing is that I should feel grateful instead of addressing what\'s not working. That\'s not a partnership — that\'s a power play."',
        explanation: 'This is a control tactic — diminishing your worth to keep you compliant. Naming the dynamic exposes it. You don\'t need to fight or flee; just see it clearly and say what it is.',
      },
      {
        id: 'md_4',
        provocation: '"I heard you talking about me to Sarah. I thought we were friends."',
        speaker: 'Friend',
        context: 'You vented to Sarah about a legitimate concern with this friend',
        timeLimitMs: 15000,
        strategies: [
          { id: 'md_4_deny', label: 'Deny', description: 'Say it didn\'t happen or was taken out of context', icon: 'close' },
          { id: 'md_4_own', label: 'Own + Redirect', description: 'Acknowledge honestly and redirect to the underlying issue', icon: 'arrow-right' },
          { id: 'md_4_blame', label: 'Blame Sarah', description: 'Say Sarah shouldn\'t have told them', icon: 'account-alert' },
          { id: 'md_4_flip', label: 'Flip It', description: 'Point out that the underlying concern is still valid', icon: 'swap-horizontal' },
        ],
        correctStrategyId: 'md_4_own',
        idealResponse: '"You\'re right, I should have come to you directly. I had a concern I didn\'t know how to bring up. Can we talk about it now?"',
        explanation: 'Own the mistake (talking behind their back) without abandoning the valid concern. This shows integrity — you\'re accountable AND honest. Don\'t let the method distract from the message.',
      },
      {
        id: 'md_5',
        provocation: '"You\'re overreacting. It was just a joke. Can\'t you take a joke?"',
        speaker: 'Colleague',
        context: 'They made a joke at your expense in a meeting',
        timeLimitMs: 12000,
        strategies: [
          { id: 'md_5_laugh', label: 'Laugh It Off', description: 'Pretend it didn\'t bother you', icon: 'emoticon' },
          { id: 'md_5_assert', label: 'Assert Your Reality', description: 'Stand firm on your experience without apologizing', icon: 'shield-check' },
          { id: 'md_5_escalate', label: 'Escalate', description: 'Report it to management', icon: 'arrow-up-bold' },
          { id: 'md_5_joke_back', label: 'Joke Back', description: 'Make a joke at their expense', icon: 'flash' },
        ],
        correctStrategyId: 'md_5_assert',
        idealResponse: '"If it lands as hurtful, it doesn\'t matter that it was intended as a joke. I\'d appreciate you not doing that in meetings."',
        explanation: '"It was just a joke" is a classic deflection that puts the blame on your reaction instead of their behavior. Assert that impact matters more than intent, and set a clear boundary.',
      },
      {
        id: 'md_6',
        provocation: '"If you really loved me, you wouldn\'t need time away from me."',
        speaker: 'Partner',
        context: 'You mentioned wanting a weekend trip with friends',
        timeLimitMs: 15000,
        strategies: [
          { id: 'md_6_prove', label: 'Prove Your Love', description: 'Cancel the trip and spend the weekend together', icon: 'heart' },
          { id: 'md_6_detach', label: 'Detach + Affirm', description: 'Separate love from constant proximity', icon: 'vector-difference' },
          { id: 'md_6_confront', label: 'Call It Out', description: 'Tell them this is controlling behavior', icon: 'alert-octagon' },
          { id: 'md_6_compromise', label: 'Compromise', description: 'Offer to shorten the trip', icon: 'scale-balance' },
        ],
        correctStrategyId: 'md_6_detach',
        idealResponse: '"I love you AND I need time with friends. Those aren\'t opposites — healthy people in healthy relationships have both."',
        explanation: 'The manipulation creates a false either/or: love me OR have your own life. The antidote is AND thinking. Healthy love includes space. Don\'t prove love by giving up autonomy.',
      },
      {
        id: 'md_7',
        provocation: '"I\'m not going to tell you again. This is how we do things here."',
        speaker: 'Senior colleague',
        context: 'You suggested a better process and they shut it down',
        timeLimitMs: 12000,
        strategies: [
          { id: 'md_7_submit', label: 'Submit', description: 'Follow the existing process without question', icon: 'check' },
          { id: 'md_7_question', label: 'Anchor to Outcome', description: 'Redirect from authority to shared goals', icon: 'target' },
          { id: 'md_7_argue', label: 'Argue', description: 'Insist your way is better', icon: 'sword-cross' },
          { id: 'md_7_go_around', label: 'Go Around', description: 'Implement your idea without telling them', icon: 'arrow-u-right-top' },
        ],
        correctStrategyId: 'md_7_question',
        idealResponse: '"I respect the established process. My goal is the same as yours — great outcomes. Can we test both approaches and let the results decide?"',
        explanation: 'Authority-based shutdowns avoid accountability. Anchoring to shared outcomes ("we both want great results") levels the playing field. Proposing a test removes ego from the equation.',
      },
      {
        id: 'md_8',
        provocation: '"I heard you might be job-hunting. Should I be worried about your commitment here?"',
        speaker: 'Manager',
        context: 'You updated your LinkedIn profile and someone noticed',
        timeLimitMs: 12000,
        strategies: [
          { id: 'md_8_deny', label: 'Deny Everything', description: 'Say you have no plans to leave', icon: 'close-circle' },
          { id: 'md_8_redirect', label: 'Redirect to Needs', description: 'Use this as an opening to discuss what would keep you', icon: 'arrow-right' },
          { id: 'md_8_confirm', label: 'Confirm', description: 'Admit you\'re looking to be honest', icon: 'check-bold' },
          { id: 'md_8_deflect', label: 'Deflect', description: 'Say you were just updating your profile', icon: 'arrow-u-right-top' },
        ],
        correctStrategyId: 'md_8_redirect',
        idealResponse: '"I\'m focused on doing great work here. I\'d love to talk about what growth looks like for me in this role — can we schedule time for that?"',
        explanation: 'Don\'t lie (damages trust) or confirm (loses leverage). Redirect the energy into a productive conversation about your future at the company. Their concern about losing you is actually leverage for getting what you want.',
      },
    ],
  },
];

export const ADVANCED_RESPONSE_SETS: FirstResponseSet[] = [
  {
    id: 'power_dynamics',
    title: 'Power Dynamics',
    description: 'Navigate high-stakes workplace and professional encounters',
    difficulty: 3,
    rounds: [
      {
        id: 'pd_1',
        provocation: '"We\'ve decided to restructure your team. Your headcount is being reduced from 8 to 4."',
        speaker: 'Director',
        context: 'Unscheduled meeting, your team just delivered record results',
        timeLimitMs: 15000,
        strategies: [
          { id: 'pd_1_protest', label: 'Protest', description: 'Point to your team\'s recent results as evidence this is wrong', icon: 'chart-line' },
          { id: 'pd_1_anchor', label: 'Anchor High', description: 'Counter with a number that makes the real ask seem reasonable', icon: 'anchor' },
          { id: 'pd_1_comply', label: 'Accept', description: 'Agree and ask how to proceed', icon: 'check' },
          { id: 'pd_1_delay', label: 'Buy Time', description: 'Ask for a week to propose alternatives', icon: 'clock-outline' },
        ],
        correctStrategyId: 'pd_1_anchor',
        idealResponse: '"I understand the pressure. Given our current project load, losing any people puts delivery at risk. Could we discuss keeping 7 and finding the savings elsewhere?"',
        explanation: 'Starting from 7 instead of fighting for 8 reframes the negotiation. You\'ve already conceded something (accepting 1 cut), which creates a sense of fairness — while your actual floor might be 6. The initial anchor shapes what feels "reasonable" for the rest of the conversation.',
      },
      {
        id: 'pd_2',
        provocation: '"I don\'t think you have the experience for this client. Maybe Sarah should lead."',
        speaker: 'Senior partner',
        context: 'Team meeting, you\'ve been preparing for this pitch for weeks',
        timeLimitMs: 12000,
        strategies: [
          { id: 'pd_2_defer', label: 'Defer', description: 'Agree that Sarah might be a better fit', icon: 'account-switch' },
          { id: 'pd_2_credentials', label: 'List Credentials', description: 'Rattle off your qualifications', icon: 'file-certificate' },
          { id: 'pd_2_strategic_vuln', label: 'Strategic Openness', description: 'Acknowledge the gap while demonstrating unique value', icon: 'shield-heart' },
          { id: 'pd_2_challenge', label: 'Challenge', description: 'Ask what specifically they think you lack', icon: 'help-circle' },
        ],
        correctStrategyId: 'pd_2_strategic_vuln',
        idealResponse: '"You\'re right that Sarah has more years with this type of client. What I bring is deep research on their specific pain points — I\'ve spent three weeks mapping their challenges. Can I walk you through what I\'ve found?"',
        explanation: 'Acknowledging the other person\'s point before presenting yours is disarming. By conceding experience, you remove the argument — and redirect to preparation, which is something you control. People trust those who can name their own limitations.',
      },
      {
        id: 'pd_3',
        provocation: '"Your proposal is good, but the budget is $50K and we both know this should cost $30K."',
        speaker: 'Client',
        context: 'Contract negotiation for consulting work, your cost is $42K',
        timeLimitMs: 12000,
        strategies: [
          { id: 'pd_3_split', label: 'Split the Difference', description: 'Offer to meet in the middle at $40K', icon: 'scale-balance' },
          { id: 'pd_3_scope', label: 'Scope Trade', description: 'Agree to their number but adjust what they get', icon: 'swap-horizontal' },
          { id: 'pd_3_justify', label: 'Justify', description: 'Break down your costs to prove the price', icon: 'calculator' },
          { id: 'pd_3_walk', label: 'Walk Away', description: 'Say you can\'t go below $50K', icon: 'exit-run' },
        ],
        correctStrategyId: 'pd_3_scope',
        idealResponse: '"I can absolutely work within $30K. Let me show you what that scope looks like — we\'d cover Phase 1 and 2. For the full deliverable including Phase 3, we\'d need to discuss the original figure."',
        explanation: 'Never negotiate on price alone — always tie price to scope. Agreeing to their number but showing what it buys reframes the conversation. Now they\'re choosing between less work for less money or full work for fair money. You haven\'t budged on value.',
      },
      {
        id: 'pd_4',
        provocation: '"I need you to fire Mike. His performance reviews will back it up."',
        speaker: 'VP',
        context: 'Private meeting. Mike is actually a solid performer who challenged the VP in a meeting last week.',
        timeLimitMs: 15000,
        strategies: [
          { id: 'pd_4_comply', label: 'Follow Orders', description: 'Begin the termination process', icon: 'check' },
          { id: 'pd_4_refuse', label: 'Refuse', description: 'Say you won\'t fire a good employee', icon: 'close-circle' },
          { id: 'pd_4_mirror', label: 'Mirror + Slow Down', description: 'Repeat their words back and create space to think', icon: 'mirror' },
          { id: 'pd_4_document', label: 'Paper Trail', description: 'Ask for the request in writing', icon: 'file-document' },
        ],
        correctStrategyId: 'pd_4_mirror',
        idealResponse: '"Fire Mike... His performance reviews will back it up?"',
        explanation: 'Mirroring — repeating the last few words as a question — forces the other person to elaborate and often reconsider. It buys you time without showing resistance. In high-pressure moments, making someone hear their own words reflected back often causes them to soften or reveal the real motivation.',
      },
      {
        id: 'pd_5',
        provocation: '"We love your work, but honestly, three other firms can do this for less."',
        speaker: 'Procurement lead',
        context: 'Final round of vendor selection, you\'re the preferred choice on quality',
        timeLimitMs: 12000,
        strategies: [
          { id: 'pd_5_discount', label: 'Offer Discount', description: 'Drop your price to compete', icon: 'sale' },
          { id: 'pd_5_loss_frame', label: 'Highlight Risk', description: 'Frame the cheaper option in terms of what they\'d lose', icon: 'alert-outline' },
          { id: 'pd_5_bluff', label: 'Call the Bluff', description: 'Say "go with them then"', icon: 'poker-chip' },
          { id: 'pd_5_add_value', label: 'Add Value', description: 'Offer extras without changing price', icon: 'plus-circle' },
        ],
        correctStrategyId: 'pd_5_loss_frame',
        idealResponse: '"I understand cost matters. Let me ask — what would it cost your team if the project was delayed by even two weeks with a less experienced firm? Our track record eliminates that risk."',
        explanation: 'People are more motivated to avoid losses than to gain benefits. Framing the cheap option as a potential loss (delays, rework, risk) is more persuasive than listing your strengths. You\'re not attacking competitors — you\'re making the risk of switching feel real.',
      },
      {
        id: 'pd_6',
        provocation: '"I appreciate your interest, but we\'ve already decided to go with an internal candidate."',
        speaker: 'Hiring manager',
        context: 'You\'re interviewing for a role you really want, third round',
        timeLimitMs: 15000,
        strategies: [
          { id: 'pd_6_accept', label: 'Accept Gracefully', description: 'Thank them and move on', icon: 'hand-wave' },
          { id: 'pd_6_plant_seed', label: 'Plant a Seed', description: 'Leave an impression that keeps the door open', icon: 'sprout' },
          { id: 'pd_6_push', label: 'Push Back', description: 'Ask why they\'re still interviewing external candidates then', icon: 'help-circle' },
          { id: 'pd_6_offer', label: 'Counter-Offer', description: 'Offer to start at a lower level or salary', icon: 'trending-down' },
        ],
        correctStrategyId: 'pd_6_plant_seed',
        idealResponse: '"I respect that decision. If things change, I\'d love to stay in the conversation. One thing I noticed — your onboarding metrics could be 30% faster with a system I\'ve built before. Happy to share the approach regardless."',
        explanation: 'Offering value with no strings attached creates a psychological pull. You\'re demonstrating competence and generosity simultaneously. People remember those who gave without being asked — and the internal candidate might not work out. Leaving value on the table is the best follow-up strategy.',
      },
      {
        id: 'pd_7',
        provocation: '"This project is behind schedule because your team dropped the ball."',
        speaker: 'Cross-functional partner',
        context: 'Stakeholder meeting. The delay was actually caused by their late requirements.',
        timeLimitMs: 12000,
        strategies: [
          { id: 'pd_7_correct', label: 'Set Record Straight', description: 'Present the timeline showing their delay', icon: 'calendar-alert' },
          { id: 'pd_7_absorb', label: 'Take the Hit', description: 'Accept blame to keep the relationship', icon: 'shield' },
          { id: 'pd_7_redirect', label: 'Redirect to Future', description: 'Skip blame and focus on the path forward', icon: 'arrow-right-bold' },
          { id: 'pd_7_collab', label: 'Shared Accountability', description: 'Reframe as a joint challenge without assigning blame', icon: 'handshake' },
        ],
        correctStrategyId: 'pd_7_collab',
        idealResponse: '"We both want this to land well. Let\'s map the blockers together — I think there were dependencies on both sides. How do we make up the two weeks?"',
        explanation: '"Both sides" gently distributes accountability without making accusations. By immediately pivoting to solution, you look like the leader in the room. The person who skips blame and focuses on fixing earns more credibility than the person who wins the blame game.',
      },
      {
        id: 'pd_8',
        provocation: '"I need your honest opinion — but between us, the CEO already loves this direction."',
        speaker: 'Product lead',
        context: 'They\'re asking you to review a strategy you think is flawed',
        timeLimitMs: 15000,
        strategies: [
          { id: 'pd_8_agree', label: 'Go Along', description: 'Say it looks great since the CEO is already bought in', icon: 'thumb-up' },
          { id: 'pd_8_honest', label: 'Be Blunt', description: 'Tell them directly what\'s wrong with it', icon: 'alert' },
          { id: 'pd_8_build', label: 'Build on It', description: 'Express support while steering toward a better version', icon: 'pencil-plus' },
          { id: 'pd_8_defer', label: 'Defer', description: 'Say you need more time to review', icon: 'clock' },
        ],
        correctStrategyId: 'pd_8_build',
        idealResponse: '"The core insight is strong — I can see why it has support. What if we pressure-tested it by adding X? That would address the one gap I see and make it bulletproof."',
        explanation: 'When power has already aligned behind an idea, opposing it directly burns political capital. Building on it lets you reshape it from within. "What if we added X" preserves their ownership while steering toward a better outcome. You\'re seen as an enhancer, not an obstacle.',
      },
    ],
  },
  {
    id: 'strategic_conversations',
    title: 'Strategic Conversations',
    description: 'Advanced interpersonal moves for high-impact social situations',
    difficulty: 4,
    rounds: [
      {
        id: 'sc_1',
        provocation: '"I don\'t see why we need to change anything. The current system works fine."',
        speaker: 'Resistant stakeholder',
        context: 'You need their buy-in for a process change that would benefit your team',
        timeLimitMs: 15000,
        strategies: [
          { id: 'sc_1_data', label: 'Present Data', description: 'Show metrics proving the current system is underperforming', icon: 'chart-bar' },
          { id: 'sc_1_identity', label: 'Identity Appeal', description: 'Frame them as the type of leader who drives innovation', icon: 'star' },
          { id: 'sc_1_force', label: 'Escalate', description: 'Go above them to get the change mandated', icon: 'arrow-up-bold' },
          { id: 'sc_1_pilot', label: 'Small Ask', description: 'Propose a tiny, low-risk pilot instead of full change', icon: 'flask' },
        ],
        correctStrategyId: 'sc_1_identity',
        idealResponse: '"You\'ve always been someone who spots what\'s next before others do. I think you\'d see the potential here — can I show you what I have in mind?"',
        explanation: 'People act consistently with how they see themselves. By framing them as an innovator and early adopter, you create a psychological pull toward agreement. They\'re not agreeing to your idea — they\'re living up to the identity you\'ve reflected back to them.',
      },
      {
        id: 'sc_2',
        provocation: '"We really can\'t afford consultants right now. Budget is frozen."',
        speaker: 'Potential client',
        context: 'You\'re trying to land a consulting engagement and they seem interested but blocked on cost',
        timeLimitMs: 12000,
        strategies: [
          { id: 'sc_2_discount', label: 'Offer Discount', description: 'Lower your rate to fit their budget', icon: 'sale' },
          { id: 'sc_2_favor', label: 'Give First', description: 'Offer a free diagnostic session to demonstrate value', icon: 'gift' },
          { id: 'sc_2_urgency', label: 'Create Urgency', description: 'Tell them your calendar is filling up fast', icon: 'clock-alert' },
          { id: 'sc_2_wait', label: 'Follow Up Later', description: 'Ask when the budget unfreezes', icon: 'calendar' },
        ],
        correctStrategyId: 'sc_2_favor',
        idealResponse: '"I hear you on budget. Let me do something — I\'ll run a quick diagnostic on your current process, no charge. If I find savings that justify the engagement, we can talk. If not, you got free insights."',
        explanation: 'Giving value first — before asking for anything — creates a natural pull toward reciprocation. The free diagnostic isn\'t charity; it\'s a strategic investment. Once they receive value, the psychological weight of receiving without giving back makes them more likely to find budget.',
      },
      {
        id: 'sc_3',
        provocation: '"I want to renegotiate my contract. I think I deserve a much higher rate."',
        speaker: 'Freelancer you manage',
        context: 'They do good work but are already at market rate',
        timeLimitMs: 15000,
        strategies: [
          { id: 'sc_3_refuse', label: 'Refuse', description: 'Tell them the current rate is fair', icon: 'close' },
          { id: 'sc_3_small_ask', label: 'Ask a Favor', description: 'Request a small concession before discussing their rate', icon: 'hand-wave' },
          { id: 'sc_3_match', label: 'Match', description: 'Agree to their rate increase', icon: 'check' },
          { id: 'sc_3_defer', label: 'Defer', description: 'Say you need to check with finance', icon: 'clock' },
        ],
        correctStrategyId: 'sc_3_small_ask',
        idealResponse: '"I want to have that conversation. Before we get into numbers — could you help me with something? I need a quick turnaround on the Henderson deliverable. Once that\'s wrapped, let\'s sit down and map out a fair path forward."',
        explanation: 'Asking someone for a favor before a negotiation subtly shifts the dynamic. Having just helped you, they feel invested in the relationship and are more receptive to a collaborative discussion rather than a confrontational demand. It also demonstrates that you value their work.',
      },
      {
        id: 'sc_4',
        provocation: '"I want a $15,000 discount on the annual contract."',
        speaker: 'Long-term client',
        context: 'Renewal negotiation, they account for 20% of your revenue',
        timeLimitMs: 12000,
        strategies: [
          { id: 'sc_4_counter', label: 'Counter Low', description: 'Offer $2,000 off and hold firm', icon: 'currency-usd-off' },
          { id: 'sc_4_big_then_small', label: 'Expand Then Trade', description: 'Propose a bigger package first, then adjust down to include a concession', icon: 'arrow-collapse-down' },
          { id: 'sc_4_refuse', label: 'Hold Price', description: 'Say the price reflects the value and you can\'t discount', icon: 'lock' },
          { id: 'sc_4_match', label: 'Give the Discount', description: 'Agree to keep the relationship', icon: 'check' },
        ],
        correctStrategyId: 'sc_4_big_then_small',
        idealResponse: '"What if we expanded the engagement to include quarterly strategy sessions — at $5K more? No? Okay, how about we keep the current scope and I can offer a $5K loyalty credit. That way you get recognized for being a long-term partner."',
        explanation: 'Starting with a larger proposal and then stepping down to a more reasonable concession makes the smaller offer feel like a genuine compromise. The client feels they\'ve won something through negotiation rather than receiving a handout. Renaming "discount" as "loyalty credit" also reframes the concession as earned.',
      },
      {
        id: 'sc_5',
        provocation: '"I need you to present first at the board meeting tomorrow."',
        speaker: 'Colleague',
        context: 'They want you to go first because presenting after someone sets the tone and is strategically advantageous',
        timeLimitMs: 12000,
        strategies: [
          { id: 'sc_5_agree', label: 'Go First', description: 'Accept and prepare a strong opening', icon: 'check' },
          { id: 'sc_5_frame', label: 'Set the Frame', description: 'Agree to go first but use it to shape how the board evaluates everything after', icon: 'format-paint' },
          { id: 'sc_5_refuse', label: 'Decline', description: 'Suggest they go first since they have seniority', icon: 'close' },
          { id: 'sc_5_flip', label: 'Flip the Order', description: 'Suggest going last is actually better and volunteer for that', icon: 'swap-vertical' },
        ],
        correctStrategyId: 'sc_5_frame',
        idealResponse: '"Happy to kick things off. I\'ll set the context for the board on what we\'re all trying to solve — that way everyone presents against the same success criteria."',
        explanation: 'Going first is a disadvantage only if you let others define the criteria. By setting the evaluative frame — "here\'s what success looks like" — you ensure every subsequent presenter is measured against YOUR standards. The person who defines the criteria often wins, regardless of presentation order.',
      },
      {
        id: 'sc_6',
        provocation: '"I\'m thinking of leaving the company. The offer from their competitor is really strong."',
        speaker: 'Your top performer',
        context: 'One-on-one meeting, they\'re clearly testing whether you\'ll counter-offer',
        timeLimitMs: 15000,
        strategies: [
          { id: 'sc_6_counter', label: 'Counter-Offer', description: 'Immediately offer more money to retain them', icon: 'currency-usd' },
          { id: 'sc_6_release', label: 'Let Them Go', description: 'Wish them well and don\'t counter', icon: 'hand-wave' },
          { id: 'sc_6_silence', label: 'Strategic Pause', description: 'Stay quiet and let them keep talking', icon: 'pause' },
          { id: 'sc_6_guilt', label: 'Guilt Trip', description: 'Remind them of everything you\'ve done for their career', icon: 'heart-broken' },
        ],
        correctStrategyId: 'sc_6_silence',
        idealResponse: '"..." (pause, hold eye contact, wait for them to continue)',
        explanation: 'When someone announces they might leave, they\'re often negotiating, not informing. Rushing to counter-offer reveals desperation and sets a precedent. Strategic silence after a big statement creates psychological pressure for the speaker to fill the gap — usually with their real concerns, which are often about more than money.',
      },
      {
        id: 'sc_7',
        provocation: '"We love your proposal but we need to think about it. We\'ll get back to you."',
        speaker: 'Decision-maker',
        context: 'End of a pitch meeting, you can feel the momentum dying',
        timeLimitMs: 12000,
        strategies: [
          { id: 'sc_7_wait', label: 'Respect Their Process', description: 'Thank them and follow up next week', icon: 'clock' },
          { id: 'sc_7_diagnose', label: 'Diagnose the Hesitation', description: 'Ask a question that surfaces what\'s really holding them back', icon: 'stethoscope' },
          { id: 'sc_7_pressure', label: 'Create Urgency', description: 'Mention that pricing is only valid for a limited time', icon: 'timer-sand' },
          { id: 'sc_7_sweeten', label: 'Add Incentive', description: 'Throw in something extra to close now', icon: 'gift' },
        ],
        correctStrategyId: 'sc_7_diagnose',
        idealResponse: '"Absolutely, take your time. Before I go — what\'s the one thing that, if I addressed it right now, would make this a yes today?"',
        explanation: 'This calibrated question does multiple things: it\'s respectful (you\'re not pressuring), it surfaces the real objection (often hidden behind "let me think"), and it gives you one last chance to solve the actual problem. Most "I need to think" responses are code for an objection they haven\'t voiced.',
      },
      {
        id: 'sc_8',
        provocation: '"I heard from someone that you disagreed with my approach in the leadership meeting."',
        speaker: 'Peer executive',
        context: 'They\'re confronting you privately. You did disagree, but constructively.',
        timeLimitMs: 15000,
        strategies: [
          { id: 'sc_8_deny', label: 'Deny', description: 'Say it was taken out of context', icon: 'close' },
          { id: 'sc_8_own_and_elevate', label: 'Own and Elevate', description: 'Acknowledge the disagreement and frame it as respect', icon: 'arrow-up' },
          { id: 'sc_8_deflect', label: 'Deflect', description: 'Redirect to who told them and question their motives', icon: 'arrow-u-right-top' },
          { id: 'sc_8_apologize', label: 'Apologize', description: 'Say sorry for any miscommunication', icon: 'hand-wave' },
        ],
        correctStrategyId: 'sc_8_own_and_elevate',
        idealResponse: '"I did push back on one aspect, yes. I wouldn\'t do that with someone whose thinking I didn\'t respect. I\'d rather challenge your ideas in the room than agree publicly and doubt privately. Can I share what I was thinking?"',
        explanation: 'Framing disagreement as a form of respect is disarming and genuine. "I only challenge people I take seriously" transforms a confrontation into a compliment. Contrasting it with the alternative (fake agreement) makes your directness look like loyalty, not opposition.',
      },
    ],
  },
];

FIRST_RESPONSE_SETS.push(...ADVANCED_RESPONSE_SETS);

export function getFirstResponseSetById(id: string): FirstResponseSet | undefined {
  return FIRST_RESPONSE_SETS.find((s) => s.id === id);
}
